Repository COS301-SE-2022/Board-Game-Companion-App, pull requests merged in 2022-05, with the labels that each got.

#6 Workspace generation code
  .editorconfig
  .eslintrc.json
  .gitignore
  .prettierignore
  .prettierrc
  .vscode/extensions.json
  angular.json
  apps/.gitkeep
  apps/board-game-companion-app-e2e/.eslintrc.json
  apps/board-game-companion-app-e2e/cypress.json
  apps/board-game-companion-app-e2e/project.json
  apps/board-game-companion-app-e2e/src/fixtures/example.json
  apps/board-game-companion-app-e2e/src/integration/app.spec.ts
  apps/board-game-companion-app-e2e/src/support/app.po.ts
  apps/board-game-companion-app-e2e/src/support/commands.ts
  apps/board-game-companion-app-e2e/src/support/index.ts
  apps/board-game-companion-app-e2e/tsconfig.json
  apps/board-game-companion-app/.browserslistrc
  apps/board-game-companion-app/.eslintrc.json
  apps/board-game-companion-app/jest.config.ts
  apps/board-game-companion-app/project.json
  apps/board-game-companion-app/src/app/app.component.css
  apps/board-game-companion-app/src/app/app.component.html
  apps/board-game-companion-app/src/app/app.component.spec.ts
  apps/board-game-companion-app/src/app/app.component.ts
  apps/board-game-companion-app/src/app/app.module.ts
  apps/board-game-companion-app/src/app/nx-welcome.component.ts
  apps/board-game-companion-app/src/assets/.gitkeep
  apps/board-game-companion-app/src/environments/environment.prod.ts
  apps/board-game-companion-app/src/environments/environment.ts
  apps/board-game-companion-app/src/favicon.ico
  apps/board-game-companion-app/src/index.html
  apps/board-game-companion-app/src/main.ts
  apps/board-game-companion-app/src/polyfills.ts
  apps/board-game-companion-app/src/styles.css
  apps/board-game-companion-app/src/test-setup.ts
  apps/board-game-companion-app/tsconfig.app.json
  apps/board-game-companion-app/tsconfig.editor.json
  apps/board-game-companion-app/tsconfig.json
  apps/board-game-companion-app/tsconfig.spec.json
  decorate-angular-cli.js
  jest.config.ts
  jest.preset.ts
  libs/.gitkeep
  nx.json
  package-lock.json
  package.json
  tools/generators/.gitkeep
  tools/tsconfig.tools.json
  tsconfig.base.json
Labels: type:enhancement, priority:high, scope:ui

#12 ⬆️ Add/update angular/nodeJS dependencies
  package-lock.json
  package.json
Labels: priority:high, scope:ui, type:cosmetic

#18 Updated the app component tests on the client
  .github/workflows/build.yml
  .github/workflows/deploy.yml
  .gitignore
  apps/client/src/app/app.component.spec.ts
Labels: type:bug, priority:medium, scope:cicd

#21 Feature/readme
  .github/workflows/build.yml
  README.md
  apps/client/src/assets/images/angular-icon.png
  apps/client/src/assets/images/heroku-logo.svg
  apps/client/src/assets/images/logo.png
  apps/client/src/assets/images/mongodb-log.png
Labels: priority:high, type:newdocumetation, scope:documentation

#22 Added service and initial Carousel code
  apps/client/src/app/app.component.html
  apps/client/src/app/app.module.ts
  libs/shared/src/lib/carousel/carousel.component.html
  libs/shared/src/lib/carousel/carousel.component.scss
  libs/shared/src/lib/carousel/carousel.component.spec.ts
  libs/shared/src/lib/carousel/carousel.component.ts
  libs/shared/src/lib/classes/search-result.spec.ts
  libs/shared/src/lib/classes/search-result.ts
  libs/shared/src/lib/services/bgg-search.service.spec.ts
  libs/shared/src/lib/services/bgg-search.service.ts
  libs/shared/src/lib/shared.module.ts
  package-lock.json
  package.json
Labels: type:enhancement, priority:high, scope:ui, scope:services

#29 Feature/collections api
  .gitignore
  apps/api/src/app/app.module.ts
  libs/api/board-games/.eslintrc.json
  libs/api/board-games/README.md
  libs/api/board-games/jest.config.ts
  libs/api/board-games/project.json
  libs/api/board-games/src/index.ts
  libs/api/board-games/src/lib/api-board-games.module.ts
  libs/api/board-games/src/lib/collections/controller/collections.controller.spec.ts
  libs/api/board-games/src/lib/collections/controller/collections.controller.ts
  libs/api/board-games/src/lib/collections/models/collection.ts
  libs/api/board-games/src/lib/collections/service/collections.service.spec.ts
  libs/api/board-games/src/lib/collections/service/collections.service.ts
  libs/api/board-games/tsconfig.json
  libs/api/board-games/tsconfig.lib.json
  libs/api/board-games/tsconfig.spec.json
  package-lock.json
  tsconfig.base.json
  workspace.json
Labels: type:enhancement, priority:high, scope:api

#35 BoardGameDetails page and css
  apps/client/src/app/app.component.html
  libs/pages/src/index.ts
  libs/pages/src/lib/board-game-details/board-game-details.component.html
  libs/pages/src/lib/board-game-details/board-game-details.component.scss
  libs/pages/src/lib/board-game-details/board-game-details.component.spec.ts
  libs/pages/src/lib/board-game-details/board-game-details.component.ts
  libs/pages/src/lib/pages.module.ts
  libs/shared/src/lib/carousel/carousel.component.html
  libs/shared/src/lib/carousel/carousel.component.scss
  libs/shared/src/lib/carousel/carousel.component.ts
Labels: type:enhancement, priority:high, scope:ui

#39 UI
  apps/client/project.json
  apps/client/src/app/app.component.html
  apps/client/src/app/app.component.spec.ts
  apps/client/src/app/app.module.ts
  apps/client/src/app/nx-welcome.component.ts
  apps/client/src/assets/Final_Logo.png
  apps/client/src/assets/globalstylesheet/global.scss
  apps/client/src/assets/images/logo.png
  apps/client/src/index.html
  apps/client/src/styles.scss
  apps/client/tailwind.config.js
  libs/shared/src/lib/carousel/carousel.component.html
  libs/shared/src/lib/carousel/carousel.component.scss
  libs/shared/src/lib/carousel/carousel.component.ts
  libs/shared/src/lib/header/header.component.html
  libs/shared/src/lib/header/header.component.scss
  package-lock.json
  package.json
  tailwind.config.js
Labels: type:bug, priority:high, scope:cicd, type:cosmetic

#38 :lipstick:(UI): Updated tailwind.config, header, index.html and carousel
  apps/client/src/app/app.component.html
  apps/client/src/app/app.component.spec.ts
  apps/client/src/app/app.module.ts
  apps/client/src/app/nx-welcome.component.ts
  apps/client/src/assets/Final_Logo.png
  apps/client/src/assets/globalstylesheet/global.scss
  apps/client/src/assets/images/logo.png
  apps/client/src/index.html
  apps/client/src/styles.scss
  apps/client/tailwind.config.js
  libs/shared/src/lib/carousel/carousel.component.html
  libs/shared/src/lib/carousel/carousel.component.scss
  libs/shared/src/lib/carousel/carousel.component.ts
  libs/shared/src/lib/header/header.component.html
  libs/shared/src/lib/header/header.component.scss
  package-lock.json
  package.json
  tailwind.config.js
Labels: priority:high, scope:ui, type:cosmetic

#40 Update header.component.html
  apps/client/project.json
  libs/shared/src/lib/header/header.component.html
Labels: priority:low, scope:ui, type:cosmetic

#41 ✨ (collections): updated collections controllers
  .github/workflows/test.yml
  apps/api/src/app/app.module.ts
  libs/api/board-games/src/lib/api-board-games.module.ts
  libs/api/board-games/src/lib/collections/controller/collections.controller.ts
  libs/api/board-games/src/lib/collections/service/collections.service.ts
Labels: type:enhancement, priority:high, scope:api

#43 :construction:Added carousel as child And created app-routing
  apps/client/src/app/app-routing.module.ts
  apps/client/src/app/app.component.html
  apps/client/src/app/app.module.ts
  libs/pages/src/lib/board-game-details/board-game-details.component.ts
  libs/pages/src/lib/home/home.component.html
  libs/pages/src/lib/home/home.component.ts
  libs/pages/src/lib/pages.module.ts
  libs/shared/src/lib/carousel/carousel.component.ts
  yarn.lock
Labels: type:enhancement, priority:high, scope:ui

#45 :poop: Carousel works with async calls
  libs/pages/src/lib/home/home.component.html
  libs/pages/src/lib/home/home.component.ts
  libs/shared/src/lib/carousel/carousel.component.ts
  libs/shared/src/lib/shared.module.ts
Labels: type:enhancement, priority:high, scope:ui

#46 🚧 (API): api updates
  apps/api/src/app/app.module.ts
  libs/api/board-games/src/lib/api-board-games.module.ts
  libs/api/board-games/src/lib/collections/controller/collections.controller.ts
  libs/api/board-games/src/lib/collections/models/collection.ts
  libs/api/board-games/src/lib/collections/service/collections.service.ts
  package.json
  yarn.lock
Labels: priority:high, scope:database, scope:api

#47 :poop:Added BoardGameDetails
  apps/client/src/app/app.component.html
  apps/client/src/app/app.component.ts
  apps/client/tailwind.config.js
  libs/pages/src/lib/board-game-details/board-game-details.component.html
  libs/pages/src/lib/board-game-details/board-game-details.component.scss
  libs/pages/src/lib/board-game-details/board-game-details.component.ts
  libs/pages/src/lib/home/home.component.html
  libs/pages/src/lib/home/home.component.ts
  libs/pages/src/lib/pages.module.ts
  libs/shared/src/lib/carousel/carousel.component.ts
Labels: type:enhancement, priority:high, scope:ui

#51 updated code coverage
  .github/workflows/coverage.yml
Labels: type:enhancement, priority:high, scope:cicd

#53 :poop:BoardGameDetails accepts id as parameter
  libs/pages/src/lib/board-game-details/board-game-details.component.ts
  libs/pages/src/lib/board-game-search/board-game-search.component.html
  libs/pages/src/lib/board-game-search/board-game-search.component.ts
  libs/shared/src/lib/carousel/carousel.component.html
  libs/shared/src/lib/carousel/carousel.component.ts
  libs/shared/src/lib/classes/search-result.ts
Labels: type:enhancement, priority:high, scope:ui

#54 :poop: Added local storage for a board game collection
  libs/pages/src/lib/board-game-details/board-game-details.component.html
  libs/pages/src/lib/board-game-details/board-game-details.component.ts
  libs/pages/src/lib/board-game-search/board-game-search.component.ts
Labels: type:enhancement, priority:high, scope:ui

#55 UI
  libs/shared/src/lib/carousel/carousel.component.html
  libs/shared/src/lib/carousel/carousel.component.ts
  libs/shared/src/lib/header/header.component.html
  libs/shared/src/lib/header/header.component.scss
Labels: priority:low, scope:ui, type:cosmetic

#56 :bug: Fixed routing issue
  libs/pages/src/lib/home/home.component.ts
  libs/shared/src/lib/carousel/carousel.component.ts
  libs/shared/src/lib/header/header.component.ts
Labels: type:bug, priority:high, scope:ui

#57 Database configuration
  .gitignore
  apps/api/src/app/app.module.ts
  package.json
  yarn.lock
Labels: priority:high, scope:database, scope:api

#58 :bug: fixed local storage
  libs/pages/src/lib/board-game-details/board-game-details.component.ts
  libs/pages/src/lib/home/home.component.ts
  libs/shared/src/lib/carousel/carousel.component.html
  libs/shared/src/lib/carousel/carousel.component.scss
  libs/shared/src/lib/carousel/carousel.component.ts
Labels: type:bug, priority:high, scope:ui

#59 UI
  libs/pages/src/lib/board-game-details/board-game-details.component.html
  libs/pages/src/lib/board-game-details/board-game-details.component.scss
  libs/pages/src/lib/board-game-search/board-game-search.component.html
  libs/pages/src/lib/board-game-search/board-game-search.component.scss
Labels: priority:low, scope:ui, type:cosmetic

#60 :bug:(UI): Removed header from app.component.html and put it in all pages
  apps/client/src/app/app.component.html
  libs/pages/src/lib/board-game-details/board-game-details.component.html
  libs/pages/src/lib/board-game-search/board-game-search.component.html
  libs/pages/src/lib/home/home.component.html
Labels: priority:high, scope:ui, type:cosmetic

#62 :white_check_mark: tests for shared module
  libs/shared/src/lib/carousel/carousel.component.spec.ts
  libs/shared/src/lib/classes/search-result.spec.ts
  libs/shared/src/lib/header/header.component.spec.ts
  libs/shared/src/lib/services/bgg-search.service.spec.ts
  libs/shared/src/lib/shared.module.ts
Labels: priority:high, scope:cicd, type:cosmetic

#64 :white_check_mark: more tests
  libs/pages/src/lib/bgg-search-service/bgg-search.service.spec.ts
  libs/pages/src/lib/board-game-details/board-game-details.component.spec.ts
  libs/pages/src/lib/home/home.component.spec.ts
Labels: priority:high, scope:ui, type:cosmetic

#63 removed coverage file
  .github/workflows/coverage.yml
  libs/pages/src/lib/bgg-search-service/bgg-search.service.spec.ts
Labels: type:enhancement, priority:high, scope:services

#37 🚧 (Login): Login Page Componets
  apps/client/src/app/app.component.ts
  apps/client/src/app/app.module.ts
  libs/pages/src/index.ts
  libs/pages/src/lib/login/Logo.png
  libs/pages/src/lib/login/image4.avif
  libs/pages/src/lib/login/login.component.html
  libs/pages/src/lib/login/login.component.scss
  libs/pages/src/lib/login/login.component.spec.ts
  libs/pages/src/lib/login/login.component.ts
  libs/pages/src/lib/pages.module.ts
  libs/pages/tsconfig.json
  package.json
  yarn.lock
Labels: priority:high, scope:ui, type:cosmetic

#65 UPdated readme
  README.md
Labels: priority:high, priority:low

#66 Login Logo Image (Included)
  libs/pages/src/lib/login/login.component.html
  libs/pages/src/lib/login/login.component.scss
Labels: priority:low, scope:ui, type:cosmetic

#67 Feature/collections api
  README.md
Labels: priority:high, type:newdocumetation, scope:documentation

#68 ReadME.md description
  README.md
Labels: priority:high, scope:documentation, type:updateDocumentation

#73 :bug: Carousel
  libs/pages/src/lib/home/home.component.ts
  libs/shared/src/lib/carousel/carousel.component.ts
Labels: type:bug, priority:medium, scope:ui

#79 :poop::lipstick:(UI): Carousel rework, addition of Collections page s…
  apps/client/src/styles.scss
  libs/pages/src/lib/board-game-details/board-game-details.component.scss
  libs/pages/src/lib/board-game-search/board-game-search.component.scss
  libs/pages/src/lib/collections/collections.component.html
  libs/pages/src/lib/collections/collections.component.scss
  libs/pages/src/lib/collections/collections.component.spec.ts
  libs/pages/src/lib/collections/collections.component.ts
  libs/pages/src/lib/pages.module.ts
  libs/shared/src/lib/carousel/carousel.component.html
  libs/shared/src/lib/carousel/carousel.component.scss
  libs/shared/src/lib/carousel/carousel.component.ts
  libs/shared/src/lib/header/header.component.html
Labels: priority:high, scope:ui, type:cosmetic

#76 🚧 Added controller to ScriptEditor functionality
  apps/api/src/app/app.module.ts
  libs/api/script-editor/.eslintrc.json
  libs/api/script-editor/README.md
  libs/api/script-editor/jest.config.ts
  libs/api/script-editor/project.json
  libs/api/script-editor/src/index.ts
  libs/api/script-editor/src/lib/api-script-editor.module.ts
  libs/api/script-editor/src/lib/controller/script-editor.controller.spec.ts
  libs/api/script-editor/src/lib/controller/script-editor.controller.ts
  libs/api/script-editor/src/lib/models/Metadata.ts
  libs/api/script-editor/src/lib/service/script-editor.service.spec.ts
  libs/api/script-editor/src/lib/service/script-editor.service.ts
  libs/api/script-editor/tsconfig.json
  libs/api/script-editor/tsconfig.lib.json
  libs/api/script-editor/tsconfig.spec.json
  package.json
  tsconfig.base.json
  workspace.json
  yarn.lock
Labels: priority:medium, scope:api

#80 💩💄(UI): Finalization of carousel, fixing of footer, cleaning up of de…
  apps/client/src/app/app.component.html
  apps/client/src/app/app.component.scss
  libs/pages/src/lib/board-game-details/board-game-details.component.html
  libs/pages/src/lib/board-game-details/board-game-details.component.scss
  libs/pages/src/lib/board-game-details/board-game-details.component.ts
  libs/pages/src/lib/board-game-search/board-game-search.component.html
  libs/pages/src/lib/collections/collections.component.html
  libs/pages/src/lib/collections/collections.component.spec.ts
  libs/pages/src/lib/home/home.component.html
  libs/shared/src/lib/carousel/carousel.component.html
  libs/shared/src/lib/carousel/carousel.component.scss
  libs/shared/src/lib/carousel/carousel.component.ts
  libs/shared/src/lib/classes/search-result.ts
Labels: priority:high, scope:ui, type:cosmetic

#81 update functionality to add to collections
  libs/pages/src/lib/add-to-collection/add-to-collection.component.html
  libs/pages/src/lib/add-to-collection/add-to-collection.component.ts
  libs/pages/src/lib/board-game-details/board-game-details.component.ts
  libs/pages/src/lib/home/home.component.ts
  libs/pages/src/lib/pages.module.ts
Labels: type:enhancement, priority:high, scope:ui

#82 Collection manager
  libs/pages/src/index.ts
  libs/pages/src/lib/add-to-collection/add-to-collection.component.html
  libs/pages/src/lib/add-to-collection/add-to-collection.component.scss
  libs/pages/src/lib/add-to-collection/add-to-collection.component.spec.ts
  libs/pages/src/lib/add-to-collection/add-to-collection.component.ts
  libs/pages/src/lib/board-game-details/board-game-details.component.ts
  libs/pages/src/lib/home/home.component.ts
  libs/pages/src/lib/pages.module.ts
  libs/shared/src/lib/shared.module.ts
Labels: type:enhancement, priority:high, scope:ui

#84 🎨 Updating controller of the script editor
  .gitignore
  libs/api/script-editor/src/lib/api-script-editor.module.ts
  libs/api/script-editor/src/lib/controller/script-editor.controller.ts
  libs/api/script-editor/src/lib/models/Metadata.ts
  libs/api/script-editor/src/lib/service/script-editor.service.ts
  package.json
  yarn.lock
Labels: type:enhancement, priority:medium, scope:database, scope:api

#87 :poop: fixes
  libs/pages/src/lib/add-to-collection/add-to-collection.component.html
  libs/pages/src/lib/add-to-collection/add-to-collection.component.ts
  libs/pages/src/lib/home/home.component.ts
  libs/shared/src/lib/carousel/carousel.component.html
  libs/shared/src/lib/carousel/carousel.component.ts
Labels: type:bug, priority:high, scope:ui

#88 :lipstick:(UI): Page addition and style rework
  libs/pages/src/lib/home/home.component.scss
  libs/pages/src/lib/pages.module.ts
  libs/pages/src/lib/view-collection/view-collection.component.html
  libs/pages/src/lib/view-collection/view-collection.component.scss
  libs/pages/src/lib/view-collection/view-collection.component.spec.ts
  libs/pages/src/lib/view-collection/view-collection.component.ts
  libs/shared/src/lib/carousel/carousel.component.scss
  libs/shared/src/lib/footer/footer.component.html
  libs/shared/src/lib/footer/footer.component.scss
  libs/shared/src/lib/header/header.component.html
  libs/shared/src/lib/header/header.component.scss
Labels: priority:low, scope:ui, type:cosmetic

#90 Collections
  libs/pages/src/lib/collections/collections.component.html
  libs/pages/src/lib/collections/collections.component.scss
  libs/pages/src/lib/collections/collections.component.ts
  libs/pages/src/lib/pages.module.ts
  libs/pages/src/lib/view-collection/view-collection.component.html
  libs/pages/src/lib/view-collection/view-collection.component.ts
Labels: type:enhancement, priority:high, scope:ui

#95 💄(UI): Style fixes
  libs/pages/src/lib/board-game-details/board-game-details.component.scss
  libs/shared/src/lib/carousel/carousel.component.html
  libs/shared/src/lib/carousel/carousel.component.scss
  libs/shared/src/lib/footer/footer.component.scss
Labels: priority:low, scope:ui, type:cosmetic

#96 Added removal functionality
  libs/pages/src/lib/view-collection/view-collection.component.html
  libs/pages/src/lib/view-collection/view-collection.component.ts
Labels: type:enhancement, priority:high, scope:ui

#98 Fix to removal
  libs/pages/src/lib/view-collection/view-collection.component.ts
Labels: type:bug, priority:high, scope:ui

#99 Editor buttons
  libs/pages/src/lib/editor/editor.component.html
  libs/pages/src/lib/editor/editor.component.scss
Labels: priority:medium, scope:ui, type:cosmetic

#100 Editor Page Button's enhancement
  libs/pages/src/lib/editor/editor.component.scss
Labels: priority:low, scope:ui, type:cosmetic

#101 Editor Page
  libs/pages/src/lib/editor/editor.component.html
  libs/pages/src/lib/editor/editor.component.ts
  package.json
  yarn.lock
Labels: type:enhancement, priority:low, scope:ui, type:cosmetic

#102 :lipstick: some styling for collections
  libs/pages/src/lib/collections/collections.component.html
  libs/pages/src/lib/collections/collections.component.scss
  libs/pages/src/lib/view-collection/view-collection.component.html
  libs/pages/src/lib/view-collection/view-collection.component.scss
Labels: priority:high, scope:ui, type:cosmetic

#103 fix to carousel
  apps/client/src/assets/images/No_image.png
  libs/shared/src/lib/carousel/carousel.component.html
  libs/shared/src/lib/carousel/carousel.component.ts
Labels: type:bug, priority:high, scope:ui

#106 💄(UI): Style reworks
  libs/pages/src/lib/add-to-collection/add-to-collection.component.html
  libs/pages/src/lib/add-to-collection/add-to-collection.component.scss
  libs/pages/src/lib/collections/collections.component.html
  libs/pages/src/lib/collections/collections.component.scss
  libs/pages/src/lib/view-collection/view-collection.component.html
  libs/pages/src/lib/view-collection/view-collection.component.scss
  libs/shared/src/lib/carousel/carousel.component.scss
  libs/shared/src/lib/header/header.component.html
  libs/shared/src/lib/header/header.component.scss
Labels: priority:medium, scope:ui, type:cosmetic
