Repository COS301-SE-2022/Board-Game-Companion-App, pull requests merged in 2022-08, with the labels that each got.

#247 Mobile view additiona
  libs/client-lib/src/lib/board-game-details/board-game-details/board-game-details.component.html
  libs/client-lib/src/lib/board-game-details/board-game-details/board-game-details.component.scss
  libs/client-lib/src/lib/collections/collections/collections.component.html
  libs/client-lib/src/lib/collections/collections/collections.component.scss
  libs/client-lib/src/lib/game-sessions/game-sessions/game-sessions.component.html
  libs/client-lib/src/lib/game-sessions/game-sessions/game-sessions.component.scss
  libs/client-lib/src/lib/script-detail/script-detail/script-detail.component.html
  libs/client-lib/src/lib/script-detail/script-detail/script-detail.component.scss
  libs/client-lib/src/lib/scripts/scripts/scripts.component.html
  libs/client-lib/src/lib/scripts/scripts/scripts.component.scss
  libs/client-lib/src/lib/session/session/session.component.html
  libs/client-lib/src/lib/session/session/session.component.scss
  libs/client-lib/src/lib/view-collection/view-collection/view-collection.component.ts
Labels: type:enhancement, priority:medium, scope:ui

#248 :bug: Fixed input in dsl
  libs/api-lib/src/lib/models/general/tokens.ts
  libs/api-lib/src/lib/services/compiler/compiler.service.ts
  libs/client-lib/src/lib/editor/editor/editor.component.ts
  templates/ActionTemplate.js
  templates/script.js
  templates/test.js
  templates/tokens.json
  uploads/development/scripts/62f0f832bf2b2a3f85a4b202/build/main.js
  uploads/development/scripts/62f0f832bf2b2a3f85a4b202/src/main.txt
Labels: type:bug, type:enhancement, priority:high, scope:api

#249 🐛 (UI) mobile view
  libs/client-lib/src/lib/script-detail/script-detail/script-detail.component.html
  libs/client-lib/src/lib/script-detail/script-detail/script-detail.component.scss
  uploads/development/scripts/62f385fe88ac5134f0204662/build/main.js
  uploads/development/scripts/62f385fe88ac5134f0204662/src/main.txt
  uploads/development/scripts/62f3860188ac5134f020466d/build/main.js
  uploads/development/scripts/62f3860188ac5134f020466d/src/main.txt
Labels: type:enhancement, priority:low, scope:ui

#252 🚧 banned list
  libs/api-lib/src/lib/services/compiler/compiler.service.ts
Labels: priority:medium

#253 :bug: Fixed await :fire: removed insecure methods
  libs/api-lib/src/lib/models/general/tokens.ts
  libs/api-lib/src/lib/services/compiler/compiler.service.ts
  templates/ActionTemplate.js
  templates/test.js
  uploads/development/scripts/62f132f727b0db9634783a03/build/main.js
  uploads/development/scripts/62f132f727b0db9634783a03/src/main.txt
Labels: type:bug, type:enhancement, priority:high, scope:api

#254 :children_crossing: :bug: improved err messages for dsl
  libs/api-lib/src/lib/services/compiler/compiler.service.ts
  libs/api-lib/src/lib/services/scripts/script.service.ts
  libs/client-lib/src/lib/editor/editor/editor.component.ts
  uploads/development/scripts/62f132f727b0db9634783a03/src/main.txt
Labels: type:bug, type:enhancement, priority:high, scope:api

#255 (editor) help doc
  apps/client/src - Shortcut.lnk
  apps/client/src/assets/images/AND.PNG
  apps/client/src/assets/images/COND.PNG
  apps/client/src/assets/images/CONTINUE.PNG
  apps/client/src/assets/images/DECL.PNG
  apps/client/src/assets/images/EQUAL.PNG
  apps/client/src/assets/images/IF.PNG
  apps/client/src/assets/images/IFELSE.PNG
  apps/client/src/assets/images/NOT.PNG
  apps/client/src/assets/images/WHILE.PNG
  apps/client/src/assets/images/arithmetic.PNG
  apps/client/src/assets/images/dataType.PNG
  apps/client/src/assets/images/logical.PNG
  libs/client-lib/src/lib/editor/editor-help/editor-help.component.html
  libs/client-lib/src/lib/editor/editor-help/editor-help.component.scss
  libs/client-lib/src/lib/editor/editor-help/editor-help.component.ts
  libs/client-lib/src/lib/script-executor/script-executor/script-executor.component.scss
  uploads/development/scripts/62f132f727b0db9634783a03/src/main.txt
Labels: priority:medium, type:newdocumetation, scope:ui, scope:documentation

#257 ✨(VDSL): Addition of VDSL sidebar
  libs/client-lib/src/lib/editor/editor-body/editor-body.component.html
  libs/client-lib/src/lib/editor/editor-body/editor-body.component.ts
  libs/client-lib/src/lib/editor/editor-side-bar/editor-side-bar.component.html
  libs/client-lib/src/lib/editor/editor-side-bar/editor-side-bar.component.ts
  libs/client-lib/src/lib/editor/editor-tool-bar/editor-tool-bar.component.html
  libs/client-lib/src/lib/editor/editor-tool-bar/editor-tool-bar.component.scss
  libs/client-lib/src/lib/editor/editor-tool-bar/editor-tool-bar.component.ts
  libs/client-lib/src/lib/editor/editor-visuals/editor-visuals.component.html
  libs/client-lib/src/lib/editor/editor-visuals/editor-visuals.component.scss
  libs/client-lib/src/lib/editor/editor-visuals/editor-visuals.component.spec.ts
  libs/client-lib/src/lib/editor/editor-visuals/editor-visuals.component.ts
  libs/client-lib/src/lib/editor/editor.module.ts
  libs/client-lib/src/lib/editor/editor/editor.component.html
  libs/client-lib/src/lib/editor/editor/editor.component.ts
  package.json
Labels: type:enhancement, priority:high, scope:ui

#262 minor fixes
  apps/client/src/assets/images/FOR.PNG
  apps/client/src/assets/images/WHILE.PNG
  libs/client-lib/src/lib/editor/editor-help/editor-help.component.html
  libs/client-lib/src/lib/editor/editor-help/editor-help.component.ts
Labels: priority:medium, type:newdocumetation, scope:documentation

#263 minor fixes
  libs/client-lib/src/lib/editor/editor-help/editor-help.component.html
Labels: priority:medium, type:newdocumetation, scope:documentation

#264 🚧 scripts implementation
  libs/client-lib/src/lib/scripts/downloads-page/downloads-page.component.html
  libs/client-lib/src/lib/scripts/downloads-page/downloads-page.component.scss
  libs/client-lib/src/lib/scripts/downloads-page/downloads-page.component.spec.ts
  libs/client-lib/src/lib/scripts/downloads-page/downloads-page.component.ts
  libs/client-lib/src/lib/scripts/main-scripts/main-scripts.component.html
  libs/client-lib/src/lib/scripts/main-scripts/main-scripts.component.scss
  libs/client-lib/src/lib/scripts/main-scripts/main-scripts.component.spec.ts
  libs/client-lib/src/lib/scripts/main-scripts/main-scripts.component.ts
  libs/client-lib/src/lib/scripts/own-scripts-page/own-scripts-page.component.html
  libs/client-lib/src/lib/scripts/own-scripts-page/own-scripts-page.component.scss
  libs/client-lib/src/lib/scripts/own-scripts-page/own-scripts-page.component.spec.ts
  libs/client-lib/src/lib/scripts/own-scripts-page/own-scripts-page.component.ts
  libs/client-lib/src/lib/scripts/scripts.module.ts
Labels: type:enhancement, priority:medium, scope:ui

#266 💄(VDSL): Drag and Drop functionality
  libs/client-lib/src/lib/editor/editor-body-visual/editor-body-visual.component.html
  libs/client-lib/src/lib/editor/editor-body-visual/editor-body-visual.component.scss
  libs/client-lib/src/lib/editor/editor-body-visual/editor-body-visual.component.ts
  libs/client-lib/src/lib/editor/editor-body/editor-body.component.ts
  libs/client-lib/src/lib/editor/editor/editor.component.ts
Labels: type:enhancement, priority:high, scope:ui

#267 💄 (editor) help doc
  apps/client/src/assets/images/Card.PNG
  apps/client/src/assets/images/PRINT.PNG
  apps/client/src/assets/images/endgame.PNG
  apps/client/src/assets/images/input.PNG
  apps/client/src/assets/images/output.PNG
  apps/client/src/assets/images/piece.PNG
  apps/client/src/assets/images/player.PNG
  apps/client/src/assets/images/state.PNG
  apps/client/src/assets/images/tile.PNG
  apps/client/src/assets/images/uiInput.PNG
  libs/client-lib/src/lib/editor/editor-help/editor-help.component.html
  libs/client-lib/src/lib/editor/editor-help/editor-help.component.scss
  libs/client-lib/src/lib/editor/editor-help/editor-help.component.ts
Labels: priority:medium, scope:documentation, type:updateDocumentation

#268 :bug: dsl fixes
  libs/api-lib/src/lib/services/compiler/compiler.service.ts
  templates/ActionTemplate.js
  templates/test.js
  uploads/development/scripts/6304be14c0a7933d955d3ecf/build/main.js
  uploads/development/scripts/6304be14c0a7933d955d3ecf/src/main.txt
Labels: type:bug, priority:high, scope:api

#269 reformat of help doc
  apps/client/src/assets/images/DECL.PNG
  apps/client/src/assets/images/EQUAL.PNG
  apps/client/src/assets/images/FOR.PNG
  apps/client/src/assets/images/arithmetic.PNG
  apps/client/src/assets/images/turn.PNG
  libs/client-lib/src/lib/editor/editor-help/editor-help.component.html
  libs/client-lib/src/lib/editor/editor-help/editor-help.component.scss
  libs/client-lib/src/lib/editor/editor-help/editor-help.component.ts
Labels: priority:medium, scope:documentation, type:cosmetic

#270 💄(VDSL): Looping structures fixed and modified display
  libs/client-lib/src/lib/editor/editor-body-visual/editor-body-visual.component.html
  libs/client-lib/src/lib/editor/editor-body-visual/editor-body-visual.component.scss
  libs/client-lib/src/lib/editor/editor-body-visual/editor-body-visual.component.ts
  libs/client-lib/src/lib/editor/editor-body-visual/element-template.ts
  libs/client-lib/src/lib/editor/editor-body-visual/loop-template.ts
  libs/client-lib/src/lib/editor/editor-body/editor-body.component.scss
  libs/client-lib/src/lib/editor/editor-body/editor-body.component.ts
  libs/client-lib/src/lib/editor/editor-visual-side-bar/editor-visual-side-bar.component.ts
  libs/client-lib/src/lib/editor/editor.module.ts
  libs/client-lib/src/lib/editor/editor/editor.component.ts
  libs/client-lib/src/lib/editor/visuals.scss
Labels: type:bug, priority:high, scope:ui, type:cosmetic

#271 added information
  apps/client/src/assets/images/nNetwork.PNG
  libs/client-lib/src/lib/editor/editor-help/editor-help.component.html
Labels: priority:medium, type:newdocumetation, scope:documentation

#272 minor fix
  libs/client-lib/src/lib/editor/editor-help/editor-help.component.html
Labels: priority:low, scope:documentation

#274 💄(VDSL): Addition of Do While loop
  libs/client-lib/src/lib/editor/editor-body-visual/editor-body-visual.component.scss
  libs/client-lib/src/lib/editor/editor-body-visual/element-template.ts
  libs/client-lib/src/lib/editor/editor-body-visual/loop-template.ts
Labels: priority:high, scope:ui, type:cosmetic

#276 🚧 Adding functionality to downloads page
  libs/api-lib/src/lib/controllers/downloads/downloads.controller.spec.ts
  libs/api-lib/src/lib/controllers/downloads/downloads.controller.ts
  libs/api-lib/src/lib/services/downloads/downloads.service.spec.ts
  libs/api-lib/src/lib/services/downloads/downloads.service.ts
  libs/client-lib/src/lib/scripts/downloads-page/downloads-page.component.html
  libs/client-lib/src/lib/scripts/downloads-page/downloads-page.component.ts
  libs/client-lib/src/lib/scripts/own-scripts-page/own-scripts-page.component.html
  libs/client-lib/src/lib/scripts/own-scripts-page/own-scripts-page.component.ts
  libs/client-lib/src/lib/shared/services/downloads/downloads.service.spec.ts
  libs/client-lib/src/lib/shared/services/downloads/downloads.service.ts
  libs/client-lib/src/lib/shared/shared.module.ts
Labels: priority:high
