Repository COS301-SE-2022/Board-Game-Companion-App, pull requests merged in 2022-09, with the labels that each got.

#277 :sparkles: Added asynchronous model calls and for loop
  libs/api-lib/src/lib/models/general/tokens.ts
  libs/api-lib/src/lib/services/compiler/compiler.service.ts
  templates/test.js
  uploads/development/scripts/6304be14c0a7933d955d3ecf/build/main.js
  uploads/development/scripts/6304be14c0a7933d955d3ecf/src/main.txt
Labels: type:bug, type:enhancement, priority:high, scope:api

#278 🐛 (viewCollection): Bug Fix
  libs/client-lib/src/lib/collections/collections/collections.component.ts
  libs/client-lib/src/lib/view-collection/view-collection/view-collection.component.ts
Labels: priority:high

#279 :sparkle: Added asynchronous script execution
  libs/client-lib/src/lib/script-executor/script-executor.module.ts
  libs/client-lib/src/lib/script-executor/script-executor/script-executor.component.html
  libs/client-lib/src/lib/script-executor/script-executor/script-executor.component.ts
  uploads/development/models/631361940c3edf25351e6849/model.json
  uploads/development/models/631361940c3edf25351e6849/model.weights.bin
  uploads/development/scripts/6304be14c0a7933d955d3ecf/build/main.js
  uploads/development/scripts/6304be14c0a7933d955d3ecf/src/main.txt
Labels: type:enhancement, priority:high, scope:ui

#282 ✨(VDSL): Players Container, collapsibile property added, looping added to players.
  libs/client-lib/src/lib/editor/editor-body-visual/editor-body-visual.component.html
  libs/client-lib/src/lib/editor/editor-body-visual/editor-body-visual.component.scss
  libs/client-lib/src/lib/editor/editor-body-visual/editor-body-visual.component.ts
  libs/client-lib/src/lib/editor/editor-body-visual/player-template.ts
  libs/client-lib/src/lib/editor/editor-body/editor-body.component.ts
  libs/client-lib/src/lib/editor/editor.module.ts
  uploads/development/scripts/6314c8660b476a987767ce40/build/main.js
Labels: type:enhancement, priority:high, scope:ui

#284 ✨(VDSL): Player add and remove buttons with card containers and buttons.
  libs/client-lib/src/lib/editor/editor-body-visual/card-template.ts
  libs/client-lib/src/lib/editor/editor-body-visual/editor-body-visual.component.html
  libs/client-lib/src/lib/editor/editor-body-visual/editor-body-visual.component.scss
  libs/client-lib/src/lib/editor/editor-body-visual/editor-body-visual.component.ts
  libs/client-lib/src/lib/editor/editor-body-visual/player-template.ts
  libs/client-lib/src/lib/editor/editor-body/editor-body.component.ts
  libs/client-lib/src/lib/editor/editor.module.ts
Labels: type:enhancement, priority:high, scope:ui

#285 🚧 Admin page updated
  libs/api-lib/src/lib/controllers/automata-scripts/automata-script.controller.ts
  libs/api-lib/src/lib/controllers/my-scripts/my-script.controller.ts
  libs/api-lib/src/lib/services/automata/automata.service.ts
  libs/api-lib/src/lib/services/my-script/my-script.service.ts
  libs/client-lib/src/lib/admin/admin-service/admin.service.ts
  libs/client-lib/src/lib/admin/admin/admin.component.html
  libs/client-lib/src/lib/admin/admin/admin.component.scss
  libs/client-lib/src/lib/admin/admin/admin.component.ts
  uploads/development/scripts/my-scripts/631710d9fc1fa4e9989cafcc/build/main.js
  uploads/development/scripts/my-scripts/631710d9fc1fa4e9989cafcc/src/main.txt
Labels: priority:high

#286 (editor): vdsl help doc
  apps/client/src/app/app.module.ts
  apps/client/src/assets/images/action.PNG
  apps/client/src/assets/images/actioneg.PNG
  apps/client/src/assets/images/board.PNG
  apps/client/src/assets/images/boardExample.PNG
  apps/client/src/assets/images/condExample.PNG
  apps/client/src/assets/images/condition.PNG
  apps/client/src/assets/images/create.PNG
  apps/client/src/assets/images/createExample.PNG
  apps/client/src/assets/images/endgameExample.PNG
  apps/client/src/assets/images/forexample.PNG
  apps/client/src/assets/images/ifexample.PNG
  apps/client/src/assets/images/ifstatement.PNG
  apps/client/src/assets/images/inputExample.PNG
  apps/client/src/assets/images/math.PNG
  apps/client/src/assets/images/mathExample.PNG
  apps/client/src/assets/images/outExample.PNG
  apps/client/src/assets/images/playerEg.PNG
  apps/client/src/assets/images/pre.PNG
  apps/client/src/assets/images/preExample.PNG
  apps/client/src/assets/images/return.PNG
  apps/client/src/assets/images/returnEg.PNG
  apps/client/src/assets/images/setExample.PNG
  apps/client/src/assets/images/setter.PNG
  apps/client/src/assets/images/t1Example.PNG
  apps/client/src/assets/images/turnEg.PNG
  apps/client/src/assets/images/visualFor.PNG
  apps/client/src/assets/images/visualPlayer.PNG
  apps/client/src/assets/images/visualTurn.PNG
  apps/client/src/assets/images/visualWhile.PNG
  apps/client/src/assets/images/visualendgame.PNG
  apps/client/src/assets/images/visualinput.PNG
  apps/client/src/assets/images/visualout.PNG
  apps/client/src/assets/images/whileexample.PNG
  libs/client-lib/src/lib/board-game-search/board-game-search/board-game-search.component.scss
  libs/client-lib/src/lib/editor/editor-help/editor-help.component.html
  libs/client-lib/src/lib/editor/editor-tool-bar/editor-tool-bar.component.html
  libs/client-lib/src/lib/editor/editor.module.ts
  libs/client-lib/src/lib/editor/visual-help/visual-help.component.html
  libs/client-lib/src/lib/editor/visual-help/visual-help.component.scss
  libs/client-lib/src/lib/editor/visual-help/visual-help.component.spec.ts
  libs/client-lib/src/lib/editor/visual-help/visual-help.component.ts
  uploads/development/scripts/my-scripts/631730397f4ec71458ac3ef3/build/main.js
  uploads/development/scripts/my-scripts/631730397f4ec71458ac3ef3/icons/tictactoe.PNG
  uploads/development/scripts/my-scripts/631730397f4ec71458ac3ef3/src/main.txt
  uploads/development/scripts/my-scripts/6317a3a77429ee0e92bbac22/build/main.js
  uploads/development/scripts/my-scripts/6317a3a77429ee0e92bbac22/icons/tictactoe.PNG
  uploads/development/scripts/my-scripts/6317a3a77429ee0e92bbac22/src/main.txt
  uploads/development/scripts/my-scripts/6317ed97088b5d758e74ba8e/build/main.js
  uploads/development/scripts/my-scripts/6317ed97088b5d758e74ba8e/icons/tictactoe.PNG
  uploads/development/scripts/my-scripts/6317ed97088b5d758e74ba8e/src/main.txt
  yarn.lock
Labels: priority:medium, type:newdocumetation, scope:documentation

#289 :lipstick: Added Styling to history
  libs/client-lib/src/lib/script-executor/script-executor/script-executor.component.ts
Labels: priority:high, scope:ui, type:cosmetic

#290 :sparkles:(VDSL): Cards, True and False section completed
  libs/client-lib/src/lib/editor/editor-body-visual/card-template.ts
  libs/client-lib/src/lib/editor/editor-body-visual/editor-body-visual.component.html
  libs/client-lib/src/lib/editor/editor-body-visual/editor-body-visual.component.scss
  libs/client-lib/src/lib/editor/editor-body-visual/editor-body-visual.component.ts
  libs/client-lib/src/lib/editor/editor-body-visual/element-template.ts
  libs/client-lib/src/lib/editor/editor-body-visual/loop-template.ts
  libs/client-lib/src/lib/editor/editor-body-visual/player-template.ts
  libs/client-lib/src/lib/editor/editor-body/editor-body.component.ts
Labels: type:enhancement, priority:high, scope:ui

#291 :sparkle: added parser functionality
  libs/api-lib/src/lib/models/general/tokens.ts
  libs/api-lib/src/lib/services/compiler/compiler.service.ts
  temporary/631b8a74fc513f3f54c503b2/main.txt
  temporary/631b8a74fc513f3f54c503b5/main.js
  temporary/631b8a74fc513f3f54c503b8/gears.jpg
  temporary/631b8ac6fc513f3f54c503fc/gears.jpg
Labels: type:enhancement, priority:high, scope:ui

#294 Update deploy-api.yml
  .github/workflows/deploy-api.yml
Labels: priority:high, scope:cicd

#295 🚀 update build.yml
  .github/workflows/build.yml
Labels: priority:high, scope:cicd

#296 🚀 config api to serve client
  .github/workflows/build.yml
  .github/workflows/deploy-api.yml
  Procfile
  apps/api/Procfile
  apps/api/src/app/app.module.ts
  apps/client/Procfile
  package.json
Labels: priority:high, scope:cicd, scope:hosting

#297 ❇️ added piece movement and integer type casting
  libs/api-lib/src/lib/models/general/tokens.ts
  libs/api-lib/src/lib/services/compiler/compiler.service.ts
  templates/script.js
Labels: type:enhancement, priority:high, scope:api

#298 ✨(VDSL): Code to VDSL basic functionality
  libs/client-lib/src/lib/editor/editor-body-visual/card-template.ts
  libs/client-lib/src/lib/editor/editor-body-visual/editor-body-visual.component.html
  libs/client-lib/src/lib/editor/editor-body-visual/editor-body-visual.component.ts
  libs/client-lib/src/lib/editor/editor-body-visual/element-template.ts
  libs/client-lib/src/lib/editor/editor-body-visual/loop-template.ts
  libs/client-lib/src/lib/editor/editor-body-visual/player-template.ts
  libs/client-lib/src/lib/editor/editor-body/editor-body.component.ts
  libs/client-lib/src/lib/editor/editor-visual-side-bar/editor-visual-side-bar.component.ts
  libs/client-lib/src/lib/editor/editor/editor.component.ts
Labels: type:enhancement, priority:high, scope:ui

#299 ✨ Added data sharing and activation for cards and endgame
  libs/api-lib/src/lib/models/general/tokens.ts
  libs/api-lib/src/lib/services/compiler/compiler.service.ts
  templates/script.js
Labels: type:enhancement, priority:high, scope:api

#300 :sparkles: Added removing array elements by index
  libs/api-lib/src/lib/models/general/tokens.ts
  libs/api-lib/src/lib/services/compiler/compiler.service.ts
Labels: type:enhancement, priority:high, scope:api

#304 :bug: misc fixes
  libs/api-lib/src/lib/models/general/tokens.ts
  libs/api-lib/src/lib/services/compiler/compiler.service.ts
Labels: type:bug, priority:high, scope:api

#306 api-controller unit tests
  apps/api/src/app/app.module.ts
  libs/api-lib/jest.config.ts
  libs/api-lib/src/index.ts
  libs/api-lib/src/lib/api-lib.module.ts
  libs/api-lib/src/lib/controllers/automata-scripts/automata-script.controller.spec.ts
  libs/api-lib/src/lib/controllers/automata-scripts/automata-script.controller.ts
  libs/api-lib/src/lib/controllers/board-collection/collections.controller.spec.ts
  libs/api-lib/src/lib/controllers/comments/comment.controller.spec.ts
  libs/api-lib/src/lib/controllers/downloads/downloads.controller.spec.ts
  libs/api-lib/src/lib/schemas/automata-script.schema.ts
  libs/client-lib/src/lib/board-game-search/bgg-search-service/bgg-search.service.spec.ts
  package.json
  yarn.lock
Labels: type:enhancement, priority:medium, scope:services

#307 :bug: more misc fixes :sparkle: monopoly script
  libs/api-lib/src/lib/services/compiler/compiler.service.ts
  templates/script.js
  templates/test.js
Labels: type:bug, type:enhancement, priority:high, scope:api

#310 Revert "Home"
  apps/client/ngsw-config.json
  apps/client/src/app/app.component.ts
  apps/client/src/app/app.module.ts
  libs/api-lib/src/lib/services/alert/alert.service.ts
  libs/client-lib/src/lib/collections/collections/collections.component.html
  libs/client-lib/src/lib/collections/collections/collections.component.ts
  libs/client-lib/src/lib/collections/create-collection/create-collection.component.ts
  libs/client-lib/src/lib/google-login/GoogleAuth/google-auth.service.ts
  libs/client-lib/src/lib/home/home.module.ts
  libs/client-lib/src/lib/home/home/home.component.html
  libs/client-lib/src/lib/home/home/home.component.scss
  libs/client-lib/src/lib/home/home/home.component.ts
  libs/client-lib/src/lib/shared/components/header/header.component.ts
  libs/client-lib/src/lib/shared/services/alert/alert.service.ts
Labels: type:bug, priority:high, scope:ui

#311 Revert "Revert "Home""
  apps/client/ngsw-config.json
  apps/client/src/app/app.component.ts
  apps/client/src/app/app.module.ts
  libs/api-lib/src/lib/services/alert/alert.service.ts
  libs/client-lib/src/lib/collections/collections/collections.component.html
  libs/client-lib/src/lib/collections/collections/collections.component.ts
  libs/client-lib/src/lib/collections/create-collection/create-collection.component.ts
  libs/client-lib/src/lib/google-login/GoogleAuth/google-auth.service.ts
  libs/client-lib/src/lib/home/home.module.ts
  libs/client-lib/src/lib/home/home/home.component.html
  libs/client-lib/src/lib/home/home/home.component.scss
  libs/client-lib/src/lib/home/home/home.component.ts
  libs/client-lib/src/lib/shared/components/header/header.component.ts
  libs/client-lib/src/lib/shared/services/alert/alert.service.ts
Labels: type:bug, priority:high, scope:ui

#312 :bug: imports fixed
  libs/client-lib/src/lib/client-lib.module.ts
  libs/client-lib/src/lib/editor/editor.module.ts
Labels: type:bug, priority:high, scope:api

#314 ✨(VDSL): Code to VDSL (If statements, for loops, returns)
  libs/client-lib/src/lib/editor/editor-body-visual/editor-body-visual.component.scss
  libs/client-lib/src/lib/editor/editor-body-visual/editor-body-visual.component.ts
  libs/client-lib/src/lib/editor/editor-body-visual/element-template.ts
  libs/client-lib/src/lib/editor/editor-body-visual/loop-template.ts
  libs/client-lib/src/lib/editor/editor-body/editor-body.component.ts
  libs/client-lib/src/lib/editor/editor/editor.component.html
  libs/client-lib/src/lib/editor/visuals.scss
Labels: type:enhancement, priority:high, scope:ui

#315 :sparkle: added player names to history
  libs/api-lib/src/lib/services/compiler/compiler.service.ts
  libs/client-lib/src/lib/editor/editor/editor.component.ts
  libs/client-lib/src/lib/script-executor/script-executor/script-executor.component.ts
  templates/script.js
Labels: type:enhancement, priority:high, scope:ui, scope:api

#317 (VDSL): Code to VDSL (while, do while, customize tile, conditions)
  libs/client-lib/src/lib/editor/editor-body-visual/editor-body-visual.component.html
  libs/client-lib/src/lib/editor/editor-body-visual/editor-body-visual.component.scss
  libs/client-lib/src/lib/editor/editor-body-visual/editor-body-visual.component.ts
  libs/client-lib/src/lib/editor/editor-body-visual/element-template.ts
  libs/client-lib/src/lib/editor/editor-body-visual/loop-template.ts
  libs/client-lib/src/lib/editor/editor-body/editor-body.component.ts
  libs/client-lib/src/lib/editor/editor/editor.component.ts
Labels: type:enhancement, priority:high, scope:ui

#318 Script executor
  libs/client-lib/src/lib/editor/editor-body/editor-body.component.ts
  libs/client-lib/src/lib/script-executor/script-executor/script-executor.component.html
  libs/client-lib/src/lib/script-executor/script-executor/script-executor.component.ts
  templates/script.js
Labels: priority:high, scope:ui, type:cosmetic

#319 🚀 Deployment
  .github/workflows/deploy-client.yml
  apps/client/src/environments/environment.prod.ts
  apps/client/src/environments/environment.ts
  libs/client-lib/src/lib/shared/services/scripts/script.service.ts
Labels: priority:high

#320 (VDSL): Code to VDSL completion
  libs/client-lib/src/lib/editor/editor-body-visual/card-template.ts
  libs/client-lib/src/lib/editor/editor-body-visual/editor-body-visual.component.html
  libs/client-lib/src/lib/editor/editor-body-visual/editor-body-visual.component.ts
  libs/client-lib/src/lib/editor/editor-body-visual/element-template.ts
  libs/client-lib/src/lib/editor/editor-body-visual/loop-template.ts
  libs/client-lib/src/lib/editor/editor-body-visual/player-template.ts
  libs/client-lib/src/lib/editor/editor-body/editor-body.component.ts
Labels: type:enhancement, priority:high, scope:ui

#321 🚀 Deployment
  libs/client-lib/src/lib/script-detail/script-detail-service/script-detail.service.ts
  libs/client-lib/src/lib/shared/services/admin/admin.service.ts
  libs/client-lib/src/lib/shared/services/alert/alert.service.ts
  libs/client-lib/src/lib/shared/services/collections/collection.service.ts
  libs/client-lib/src/lib/shared/services/comments/comment.service.ts
  libs/client-lib/src/lib/shared/services/downloads/downloads.service.ts
  libs/client-lib/src/lib/shared/services/editor/editor.service.ts
  libs/client-lib/src/lib/shared/services/models/models.service.ts
  libs/client-lib/src/lib/shared/services/reports/report.service.ts
Labels: priority:high

#322 🚀 socket environment config
  apps/client/src/app/app.module.ts
  apps/client/src/environments/environment.prod.ts
  apps/client/src/environments/environment.ts
Labels: priority:high

#323 🐛(VDSL): VDSL performance issue fixed
  libs/client-lib/src/lib/editor/editor-body/editor-body.component.ts
Labels: type:bug, priority:high, scope:ui

#328 🚀 Testing
  apps/client/src/app/app.component.spec.ts
  libs/client-lib/src/lib/client-lib-routing.module.spec.ts
  libs/client-lib/src/lib/editor/editor-help/editor-help.component.spec.ts
  libs/client-lib/src/lib/editor/visual-help/visual-help.component.spec.ts
  libs/client-lib/src/lib/home/home/home.component.spec.ts
  libs/client-lib/src/lib/scripts/automata-scripts/automata-scripts.component.spec.ts
  libs/client-lib/src/lib/scripts/create-script/create-scripts.component.spec.ts
  libs/client-lib/src/lib/shared/components/header/header.component.spec.ts
  libs/client-lib/src/lib/shared/components/input-interface/input-interface.component.spec.ts
  libs/client-lib/src/lib/shared/services/alert/alert.service.spec.ts
  libs/client-lib/src/lib/shared/services/bgg-search/bgg-search.service.spec.ts
  libs/client-lib/src/lib/shared/services/collections/collection.service.spec.ts
  libs/client-lib/src/lib/shared/services/models/models.service.spec.ts
  libs/client-lib/src/lib/shared/services/reports/report.service.spec.ts
  libs/client-lib/src/lib/shared/services/scripts/script.service.spec.ts
  libs/client-lib/src/lib/shared/services/storage/storage.service.spec.ts
  libs/client-lib/src/test-setup.ts
  package.json
  yarn.lock
Labels: priority:high

#330 :bug: fixed bugs on monopoly script
  libs/api-lib/src/lib/services/compiler/compiler.service.ts
  libs/client-lib/src/lib/game-sessions/game-sessions/game-sessions.component.scss
  libs/client-lib/src/lib/home/home/home.component.ts
  libs/client-lib/src/lib/script-executor/script-executor/script-executor.component.ts
  templates/script.js
Labels: type:bug, priority:high, scope:api

#331 🚀 : Change to URL config
  apps/client/src/app/app.module.ts
  libs/client-lib/src/lib/script-detail/script-detail-service/script-detail.service.ts
  libs/client-lib/src/lib/shared/services/admin/admin.service.ts
  libs/client-lib/src/lib/shared/services/alert/alert.service.ts
  libs/client-lib/src/lib/shared/services/collections/collection.service.ts
  libs/client-lib/src/lib/shared/services/comments/comment.service.ts
  libs/client-lib/src/lib/shared/services/downloads/downloads.service.ts
  libs/client-lib/src/lib/shared/services/editor/editor.service.ts
  libs/client-lib/src/lib/shared/services/models/models.service.ts
  libs/client-lib/src/lib/shared/services/reports/report.service.ts
  libs/client-lib/src/lib/shared/services/scripts/script.service.ts
Labels: priority:high

#332 ✅ Testing
  libs/client-lib/src/lib/admin/admin-others/admin-others.component.spec.ts
  libs/client-lib/src/lib/admin/admin-reports/admin-reports.component.spec.ts
  libs/client-lib/src/lib/admin/admin-scripts/admin-scripts.component.spec.ts
  libs/client-lib/src/lib/admin/admin-service/admin.service.spec.ts
  libs/client-lib/src/lib/admin/admin-users/admin-users.component.spec.ts
  libs/client-lib/src/lib/admin/admin/admin.component.spec.ts
  libs/client-lib/src/lib/admin/admin/admin.component.ts
  libs/client-lib/src/lib/admin/warn-form/warn-form.component.spec.ts
  libs/client-lib/src/lib/board-game-search/board-game-search/board-game-search.component.spec.ts
  libs/client-lib/src/lib/client-lib-routing.module.spec.ts
  libs/client-lib/src/lib/editor/editor-tool-bar/editor-tool-bar.component.spec.ts
  libs/client-lib/src/lib/script-detail/comment/comment.component.spec.ts
  libs/client-lib/src/lib/scripts/automata-scripts/automata-scripts.component.spec.ts
  libs/client-lib/src/lib/shared/components/header/header.component.spec.ts
  libs/client-lib/src/lib/shared/services/admin/admin.service.spec.ts
  libs/client-lib/src/lib/shared/services/alert/alert.service.spec.ts
  libs/client-lib/src/lib/shared/services/comments/comment.service.spec.ts
  libs/client-lib/src/lib/shared/services/reports/report.service.spec.ts
  libs/client-lib/src/lib/shared/services/scripts/script.service.spec.ts
  package.json
  yarn.lock
Labels: priority:high

#333 ✨ Sessions
  libs/client-lib/src/index.ts
  libs/client-lib/src/lib/client-lib-routing.module.ts
  libs/client-lib/src/lib/client-lib.module.ts
  libs/client-lib/src/lib/script-detail/script-detail/script-detail.component.html
  libs/client-lib/src/lib/script-detail/script-detail/script-detail.component.scss
  libs/client-lib/src/lib/script-executor/script-executor/script-executor.component.html
  libs/client-lib/src/lib/script-executor/script-executor/script-executor.component.ts
  libs/client-lib/src/lib/session/session.module.ts
  libs/client-lib/src/lib/session/session/session.component.html
  libs/client-lib/src/lib/session/session/session.component.scss
  libs/client-lib/src/lib/session/session/session.component.spec.ts
  libs/client-lib/src/lib/session/session/session.component.ts
Labels: type:enhancement, priority:high, scope:ui, scope:api

#335 (VDSL): Visual completion and start of VDSL to code
  apps/client/src/assets/globalstylesheet/global.scss
  libs/client-lib/src/lib/editor/editor-body-visual/card-template.ts
  libs/client-lib/src/lib/editor/editor-body-visual/editor-body-visual.component.html
  libs/client-lib/src/lib/editor/editor-body-visual/editor-body-visual.component.scss
  libs/client-lib/src/lib/editor/editor-body-visual/editor-body-visual.component.ts
  libs/client-lib/src/lib/editor/editor-body-visual/element-template.ts
  libs/client-lib/src/lib/editor/editor-body-visual/loop-template.ts
  libs/client-lib/src/lib/editor/editor-body-visual/player-template.ts
  libs/client-lib/src/lib/editor/editor-body/editor-body.component.html
  libs/client-lib/src/lib/editor/editor-body/editor-body.component.ts
  libs/client-lib/src/lib/editor/editor-visual-side-bar/editor-visual-side-bar.component.scss
  libs/client-lib/src/lib/editor/visuals.scss
Labels: type:bug, priority:high, scope:ui

#336 (tests)
  libs/api-lib/jest.config.ts
  libs/api-lib/src/lib/controllers/automata-scripts/automata-script.controller.spec.ts
  libs/api-lib/src/lib/controllers/board-collection/collections.controller.spec.ts
  libs/api-lib/src/lib/controllers/comments/comment.controller.spec.ts
  libs/api-lib/src/lib/controllers/editor/editor.controller.spec.ts
  libs/api-lib/src/lib/controllers/file-manager/file-manager.controller.spec.ts
  libs/api-lib/src/lib/controllers/models/models.controller.spec.ts
  libs/api-lib/src/lib/controllers/my-scripts/my-script.controller.spec.ts
  libs/api-lib/src/lib/services/alert/alert.service.spec.ts
  libs/api-lib/src/lib/services/automata/automata.service.spec.ts
  libs/api-lib/src/lib/services/collection/collections.service.spec.ts
  libs/api-lib/src/lib/services/comments/comment.service.spec.ts
  libs/api-lib/src/lib/services/compiler/compiler.service.spec.ts
  libs/api-lib/src/lib/services/downloads/downloads.service.spec.ts
  libs/api-lib/src/lib/services/editor/editor.service.spec.ts
  libs/api-lib/src/lib/services/local-storage/local-storage.service.spec.ts
  libs/api-lib/src/lib/services/models/models.service.spec.ts
  libs/api-lib/src/lib/services/mongodb-storage/mongodb-storage.service.spec.ts
  libs/api-lib/src/lib/services/my-script/my-script.service.spec.ts
  libs/api-lib/src/lib/services/ratings/rating.service.spec.ts
  libs/api-lib/src/lib/services/reports/report.service.spec.ts
  libs/client-lib/src/lib/shared/components/footer/footer.component.scss
  libs/client-lib/src/lib/shared/services/editor/editor.service.spec.ts
  libs/client-lib/src/lib/shared/services/storage/storage.service.spec.ts
  package.json
  yarn.lock
Labels: scope:services, type:cosmetic

#337 Visual Fixes
  libs/client-lib/src/lib/script-detail/script-detail/script-detail.component.html
  libs/client-lib/src/lib/script-detail/script-detail/script-detail.component.scss
  libs/client-lib/src/lib/shared/components/footer/footer.component.html
  libs/client-lib/src/lib/shared/components/footer/footer.component.scss
  libs/client-lib/src/lib/shared/components/header/header.component.html
  libs/client-lib/src/lib/shared/components/header/header.component.scss
Labels: priority:high, scope:ui, type:cosmetic

#338 Testing
  apps/client/src/app/app.component.spec.ts
  libs/api-lib/src/lib/controllers/models/models.controller.spec.ts
  libs/api-lib/src/lib/controllers/my-scripts/my-script.controller.spec.ts
  libs/api-lib/src/lib/controllers/report/report.controller.spec.ts
  libs/api-lib/src/lib/services/admin/admin.service.spec.ts
  libs/api-lib/src/lib/services/alert/alert.service.spec.ts
  libs/api-lib/src/lib/services/automata/automata.service.spec.ts
  libs/api-lib/src/lib/services/collection/collections.service.spec.ts
  libs/api-lib/src/lib/services/comments/comment.service.spec.ts
  libs/api-lib/src/lib/services/downloads/downloads.service.spec.ts
  libs/api-lib/src/lib/services/editor/editor.service.spec.ts
  libs/api-lib/src/lib/services/local-storage/local-storage.service.spec.ts
  libs/api-lib/src/lib/services/models/models.service.spec.ts
  libs/api-lib/src/lib/services/mongodb-storage/mongodb-storage.service.spec.ts
  libs/api-lib/src/lib/services/my-script/my-script.service.spec.ts
  libs/api-lib/src/lib/services/ratings/rating.service.spec.ts
  libs/api-lib/src/lib/services/reports/report.service.spec.ts
  libs/api-lib/src/lib/services/socket/socket.gateway.spec.ts
Labels: type:enhancement, priority:medium, scope:services

#339 💄Game Sessions and Session page restyle
  libs/client-lib/src/lib/board-game-search/board-game-search/board-game-search.component.html
  libs/client-lib/src/lib/board-game-search/board-game-search/board-game-search.component.scss
  libs/client-lib/src/lib/game-sessions/game-sessions/game-sessions.component.html
  libs/client-lib/src/lib/game-sessions/game-sessions/game-sessions.component.scss
  libs/client-lib/src/lib/game-sessions/game-sessions/game-sessions.component.ts
  libs/client-lib/src/lib/script-detail/script-detail/script-detail.component.html
  libs/client-lib/src/lib/script-detail/script-detail/script-detail.component.scss
  libs/client-lib/src/lib/script-executor/script-executor/script-executor.component.ts
  libs/client-lib/src/lib/session/session/session.component.html
  libs/client-lib/src/lib/session/session/session.component.scss
Labels: priority:high, scope:ui, type:cosmetic

#340 tests
  libs/api-lib/src/lib/controllers/admin/admin.controller.spec.ts
  libs/api-lib/src/lib/controllers/alert/alert.controller.spec.ts
Labels: priority:medium, scope:services

#346 ✨Script service modification and session script view functionality.
  libs/client-lib/src/lib/script-executor/script-executor/script-executor.component.ts
  libs/client-lib/src/lib/scripts/download-scripts/download-scripts.component.ts
  libs/client-lib/src/lib/session/session/session.component.html
  libs/client-lib/src/lib/session/session/session.component.scss
  libs/client-lib/src/lib/session/session/session.component.ts
  libs/client-lib/src/lib/shared/services/scripts/script.service.ts
Labels: type:enhancement, priority:high, scope:ui, type:cosmetic

#347 Testing
  libs/api-lib/src/lib/controllers/admin/admin.controller.spec.ts
  libs/api-lib/src/lib/controllers/automata-scripts/automata-script.controller.spec.ts
Labels: priority:medium

#348 Testing
  README.md
  libs/api-lib/src/lib/controllers/comments/comment.controller.spec.ts
  libs/api-lib/src/lib/controllers/downloads/downloads.controller.spec.ts
  libs/api-lib/src/lib/controllers/editor/editor.controller.spec.ts
  libs/api-lib/src/lib/controllers/file-manager/file-manager.controller.spec.ts
  libs/api-lib/src/lib/controllers/my-scripts/my-script.controller.spec.ts
  libs/api-lib/src/lib/controllers/report/report.controller.spec.ts
  libs/api-lib/src/lib/services/admin/admin.service.spec.ts
  libs/api-lib/src/lib/services/alert/alert.service.spec.ts
  libs/api-lib/src/lib/services/automata/automata.service.spec.ts
  libs/api-lib/src/lib/services/collection/collections.service.spec.ts
  libs/api-lib/src/lib/services/comments/comment.service.spec.ts
  libs/api-lib/src/lib/services/downloads/downloads.service.spec.ts
  libs/api-lib/src/lib/services/editor/editor.service.spec.ts
  libs/api-lib/src/lib/services/local-storage/local-storage.service.spec.ts
  libs/api-lib/src/lib/services/models/models.service.spec.ts
  libs/api-lib/src/lib/services/mongodb-storage/mongodb-storage.service.spec.ts
  libs/api-lib/src/lib/services/my-script/my-script.service.spec.ts
  libs/api-lib/src/lib/services/ratings/rating.service.spec.ts
  libs/api-lib/src/lib/services/reports/report.service.spec.ts
  libs/api-lib/src/lib/services/socket/socket.gateway.spec.ts
  libs/client-lib/src/lib/admin/admin-reports/admin-reports.component.spec.ts
  libs/client-lib/src/lib/admin/warn-form/warn-form.component.spec.ts
  libs/client-lib/src/lib/client-lib-routing.module.spec.ts
  libs/client-lib/src/lib/models/models/models.component.spec.ts
  libs/client-lib/src/lib/scripts/create-script/create-scripts.component.spec.ts
  libs/client-lib/src/lib/scripts/create-script/create-scripts.component.ts
  libs/client-lib/src/lib/shared/components/header/header.component.ts
  libs/client-lib/src/lib/shared/services/admin/admin.service.spec.ts
  libs/client-lib/src/lib/shared/services/models/models.service.spec.ts
Labels: priority:high

#349 🐛 (tests) Dependency issues
  libs/client-lib/src/lib/collections/create-collection/create-collection.component.spec.ts
  libs/client-lib/src/lib/home/home/home.component.spec.ts
  libs/client-lib/src/lib/shared/services/scripts/script.service.ts
Labels: priority:high

#350 fix
  .github/workflows/test.yml
  libs/api-lib/jest.config.ts
  libs/api-lib/src/lib/controllers/comments/comment.controller.spec.ts
  libs/api-lib/src/lib/services/ratings/rating.service.spec.ts
  libs/client-lib/src/lib/board-game-search/board-game-search/board-game-search.component.scss
  someKey
  uploads/development/desktop/storagescript12
Labels: priority:low

#351 Vdsl
  libs/client-lib/src/lib/editor/editor-body-visual/card-template.ts
  libs/client-lib/src/lib/editor/editor-body-visual/editor-body-visual.component.html
  libs/client-lib/src/lib/editor/editor-body-visual/editor-body-visual.component.ts
  libs/client-lib/src/lib/editor/editor-body-visual/element-template.ts
  libs/client-lib/src/lib/editor/editor-body-visual/player-template.ts
  libs/client-lib/src/lib/editor/editor-body/editor-body.component.html
  libs/client-lib/src/lib/editor/editor-body/editor-body.component.ts
Labels: type:enhancement, priority:high, scope:ui

#352 Vdsl
  libs/client-lib/src/lib/editor/editor-body-visual/editor-body-visual.component.ts
  libs/client-lib/src/lib/editor/editor-body-visual/element-template.ts
  libs/client-lib/src/lib/editor/editor-body/editor-body.component.ts
Labels: type:enhancement, priority:high, scope:ui

#353 Vdsl
  libs/client-lib/src/lib/editor/editor-body/editor-body.component.ts
Labels: type:enhancement, priority:high, scope:ui
