Repository COS301-SE-2022/Board-Game-Companion-App, pull requests merged in 2022-06, with the labels that each got.

#118 :bug: Login working
  libs/api-lib/src/lib/api-lib.module.ts
  libs/api-lib/src/lib/services/GoogleAuth/google-auth.service.spec.ts
  libs/api-lib/src/lib/services/GoogleAuth/google-auth.service.ts
  libs/client-lib/src/index.ts
  libs/client-lib/src/lib/client-lib-routing.module.ts
  libs/client-lib/src/lib/client-lib.module.ts
  libs/client-lib/src/lib/google-login/google-login.component.html
  libs/client-lib/src/lib/google-login/google-login.component.scss
  libs/client-lib/src/lib/google-login/google-login.component.spec.ts
  libs/client-lib/src/lib/google-login/google-login.component.ts
  libs/client-lib/src/lib/google-login/google-login.module.ts
  libs/client-lib/src/lib/google-login/image4.avif
  libs/client-lib/src/lib/shared/components/header/header.component.html
  libs/client-lib/src/lib/shared/components/header/header.component.ts
  libs/client-lib/src/lib/shared/shared.module.ts
  package.json
  yarn.lock
Labels: type:bug, type:enhancement, priority:high, scope:ui, scope:services

#119 Updates to the script-editor controller
  libs/api-lib/src/lib/controllers/script-editor/script-editor.controller.ts
  libs/api-lib/src/lib/schemas/Metadata.ts
  libs/client-lib/src/lib/admin/admin-service/admin.service.ts
  libs/client-lib/src/lib/admin/admin/admin.component.html
  libs/client-lib/src/lib/admin/admin/admin.component.ts
Labels: priority:medium, scope:ui, scope:api

#122 :bug: moved GoogleAuth service
  libs/api-lib/src/lib/api-lib.module.ts
  libs/client-lib/src/lib/google-login/GoogleAuth/google-auth.service.spec.ts
  libs/client-lib/src/lib/google-login/GoogleAuth/google-auth.service.ts
  libs/client-lib/src/lib/google-login/google-login.component.ts
  libs/client-lib/src/lib/google-login/google-login.module.ts
  libs/client-lib/src/lib/shared/components/header/header.component.ts
  libs/client-lib/src/lib/shared/shared.module.ts
Labels: type:bug, priority:high, scope:services

#123 :sparkles:: Game sessions and Session page
  libs/client-lib/src/lib/client-lib-routing.module.ts
  libs/client-lib/src/lib/collections/collections/collections.component.ts
  libs/client-lib/src/lib/game-sessions/game-sessions.module.ts
  libs/client-lib/src/lib/game-sessions/game-sessions/game-sessions.component.html
  libs/client-lib/src/lib/game-sessions/game-sessions/game-sessions.component.scss
  libs/client-lib/src/lib/game-sessions/game-sessions/game-sessions.component.spec.ts
  libs/client-lib/src/lib/game-sessions/game-sessions/game-sessions.component.ts
  libs/client-lib/src/lib/session/session.module.ts
  libs/client-lib/src/lib/session/session/session.component.html
  libs/client-lib/src/lib/session/session/session.component.scss
  libs/client-lib/src/lib/session/session/session.component.spec.ts
  libs/client-lib/src/lib/session/session/session.component.ts
  libs/client-lib/src/lib/shared/components/footer/footer.component.scss
  libs/client-lib/src/lib/shared/components/header/header.component.html
  libs/client-lib/src/lib/shared/models/fetch-session-results.ts
Labels: type:enhancement, priority:high, scope:ui

#111 Toolbar options to accommodate source code
  apps/api/src/app/app.controller.ts
  apps/api/src/app/app.module.ts
  libs/api-lib/src/lib/controllers/script-editor/script-editor.controller.ts
  libs/api-lib/src/lib/schemas/Metadata.ts
  libs/api-lib/src/lib/services/editor/script-editor.service.ts
  libs/client-lib/src/lib/admin/admin/admin.component.html
  libs/client-lib/src/lib/admin/admin/admin.component.ts
  libs/client-lib/src/lib/editor/editor-service/editor.service.spec.ts
  libs/client-lib/src/lib/editor/editor-service/editor.service.ts
  libs/client-lib/src/lib/editor/editor.module.ts
  libs/client-lib/src/lib/editor/editor/editor.component.html
  libs/client-lib/src/lib/editor/editor/editor.component.ts
  libs/client-lib/src/lib/home/home/home.component.ts
  libs/client-lib/src/lib/shared/components/header/header.component.ts
Labels: type:enhancement, priority:medium, scope:ui

#126 updates
  libs/client-lib/src/lib/script-executor/script-executor/script-executor.component.html
  libs/client-lib/src/lib/script-executor/script-executor/script-executor.component.ts
  libs/client-lib/src/lib/script-executor/script-executor/test.js
  libs/client-lib/src/lib/script-executor/script-executor/test.module.ts
Labels: type:enhancement, priority:high, scope:ui

#127 Update script-executor.component.ts
  libs/client-lib/src/lib/script-executor/script-executor/script-executor.component.ts
Labels: type:enhancement, priority:high, scope:ui

#128 🚧 updates to the script-editor service
  libs/api-lib/src/lib/api-lib.module.ts
  libs/api-lib/src/lib/controllers/script-editor/script-editor.controller.ts
  libs/api-lib/src/lib/services/editor/script-editor.service.ts
  uploads/scripts/files/ef8178ee-3359-454e-a985-79ca6309290c/main.ts
Labels: priority:high, scope:database, scope:services, scope:api

#129 🔥 🔥 Removed static data from admin files
  libs/api-lib/src/lib/schemas/Metadata.ts
  libs/client-lib/src/lib/admin/admin-service/admin.service.ts
  libs/client-lib/src/lib/admin/admin/admin.component.html
  libs/client-lib/src/lib/admin/admin/admin.component.ts
Labels: priority:high, scope:ui, scope:services

#132 Editor page create button
  libs/client-lib/src/lib/editor/editor/editor.component.html
  libs/client-lib/src/lib/editor/editor/editor.component.scss
  libs/client-lib/src/lib/editor/editor/editor.component.ts
Labels: type:enhancement, priority:low, scope:ui

#133 Run Button
  libs/client-lib/src/lib/editor/editor/editor.component.html
  libs/client-lib/src/lib/editor/editor/editor.component.ts
Labels: type:enhancement, priority:low, scope:ui

#137 Editor-Proper
  libs/client-lib/src/lib/editor/editor/editor.component.html
  libs/client-lib/src/lib/editor/editor/editor.component.scss
  libs/client-lib/src/lib/editor/editor/editor.component.ts
Labels: priority:high, scope:services

#140 :bug:(API/UI): Styles added, Pathing redone
  libs/api-lib/src/lib/controllers/script/script.controller.ts
  libs/api-lib/src/lib/services/scripts/script.service.ts
  libs/client-lib/src/lib/script-executor/script-executor/script-executor.component.html
  libs/client-lib/src/lib/script-executor/script-executor/script-executor.component.scss
  libs/uploads/src/lib/scripts/files/012b70c7-74c6-467c-ae04-681b7e361f3b/test.module.ts
  libs/uploads/src/lib/scripts/files/96a35639-766b-480b-94bb-2c9e6da282db/main.module.ts
  libs/uploads/src/lib/scripts/files/ef8178ee-3359-454e-a985-79ca6309290c/main.ts
  libs/uploads/src/lib/scripts/files/ef8178ee-3359-454e-a985-79ca6309290c/math.ts
  libs/uploads/src/lib/scripts/files/ef8178ee-3359-454e-a985-79ca6309290c/sticks.ts
Labels: type:bug, priority:high, scope:ui, scope:services, type:cosmetic

#143 Script runner
  libs/api-lib/src/lib/services/scripts/script.service.ts
  libs/client-lib/src/lib/script-executor/script-executor/script-executor.component.ts
  libs/uploads/src/lib/scripts/files/0292181a-8499-47d5-82ea-0da9bacf8ed3/main.module.ts
  libs/uploads/src/lib/scripts/files/dbee8955-4349-412f-9739-931fc3a5c7dd/main.module.ts
  libs/uploads/src/lib/scripts/files/dc1c7f9a-7f95-40c7-bcc7-e04f9a63f560/main.module.ts
  libs/uploads/src/lib/scripts/icons/dbee8955-4349-412f-9739-931fc3a5c7dd/No_image.png
  libs/uploads/src/lib/scripts/icons/dbee8955-4349-412f-9739-931fc3a5c7dd/logo.png
  libs/uploads/src/lib/scripts/icons/dc1c7f9a-7f95-40c7-bcc7-e04f9a63f560/angular-icon.png
  libs/uploads/src/lib/uploads.module.ts
Labels: type:enhancement, priority:high, scope:ui

#144 💄(UI): Game sessions Update, style update
  libs/client-lib/src/lib/script-executor/script-executor/script-executor.component.html
  libs/client-lib/src/lib/script-executor/script-executor/script-executor.component.scss
  libs/client-lib/src/lib/script-executor/script-executor/script-executor.component.ts
  libs/client-lib/src/lib/shared/components/header/header.component.html
  libs/client-lib/src/lib/shared/components/header/header.component.ts
  libs/uploads/src/lib/scripts/icons/7af7ef45-e542-44cc-b13a-9ce7485840ce/BGC.png
Labels: type:enhancement, priority:high, scope:ui, scope:api, type:cosmetic

#145 :bug:(UI): Game sessions fix
  libs/client-lib/src/lib/script-executor/script-executor/script-executor.component.ts
Labels: type:bug, priority:high, scope:ui, type:cosmetic

#147 🐛(UI): game sessions fix
  libs/client-lib/src/lib/script-executor/script-executor/script-executor.component.ts
Labels: type:bug, priority:high, scope:ui

#148 🐛(UI): Game Sessions final fix
  libs/client-lib/src/lib/script-executor/script-executor/script-executor.component.ts
Labels: type:bug, priority:high, scope:ui

#151 🔧 updated jest config file
  libs/client-lib/jest.config.ts
  libs/client-lib/src/lib/add-to-collection/add-to-collection/add-to-collection.component.spec.ts
  libs/client-lib/src/lib/admin/admin-service/admin.service.spec.ts
  libs/client-lib/src/lib/admin/admin/admin.component.spec.ts
  libs/client-lib/src/lib/board-game-details/board-game-details/board-game-details.component.spec.ts
  libs/client-lib/src/lib/collections/collections/collections.component.spec.ts
  libs/client-lib/src/lib/editor/editor-service/editor.service.spec.ts
  libs/client-lib/src/lib/editor/editor/editor.component.spec.ts
  libs/client-lib/src/lib/game-sessions/game-sessions/game-sessions.component.spec.ts
  libs/client-lib/src/lib/google-login/GoogleAuth/google-auth.service.spec.ts
  libs/client-lib/src/lib/google-login/google-login.component.spec.ts
  libs/client-lib/src/lib/home/carousel/carousel.component.spec.ts
  libs/client-lib/src/lib/home/home/home.component.spec.ts
  libs/client-lib/src/lib/script-detail/script-detail-service/script-detail.service.spec.ts
  libs/client-lib/src/lib/script-detail/script-detail/script-detail.component.spec.ts
  libs/client-lib/src/lib/script-executor/script-executor/script-executor.component.spec.ts
  libs/client-lib/src/lib/scripts/create-script/create-scripts.component.spec.ts
  libs/client-lib/src/lib/scripts/scripts/scripts.component.spec.ts
  libs/client-lib/src/lib/scripts/tool-bar/tool-bar.component.spec.ts
  libs/client-lib/src/lib/scripts/update-script/update-scripts.component.spec.ts
  libs/client-lib/src/lib/session/session/session.component.spec.ts
  libs/client-lib/src/lib/shared/components/header/header.component.spec.ts
  libs/client-lib/src/lib/view-collection/view-collection/view-collection.component.spec.ts
  libs/client-lib/src/test-setup.ts
Labels: priority:medium, scope:cicd
