Repository COS301-SE-2022/Board-Game-Companion-App, pull requests merged in 2022-10, with the labels that each got.

#367 ✨(VDSL): create, set, output, input, return ,method and if partial elements now editable
  libs/client-lib/src/lib/editor/editor-body-visual/card-template.ts
  libs/client-lib/src/lib/editor/editor-body-visual/editor-body-visual.component.html
  libs/client-lib/src/lib/editor/editor-body-visual/editor-body-visual.component.scss
  libs/client-lib/src/lib/editor/editor-body-visual/editor-body-visual.component.ts
  libs/client-lib/src/lib/editor/editor-body-visual/element-template.ts
  libs/client-lib/src/lib/editor/editor-body-visual/loop-template.ts
  libs/client-lib/src/lib/editor/editor-body-visual/player-template.ts
  libs/client-lib/src/lib/editor/editor-body/editor-body.component.html
  libs/client-lib/src/lib/editor/editor-body/editor-body.component.ts
Labels: type:enhancement, priority:high, scope:ui

#369 ✨(VDSL): player and card containers have editable elements.
  libs/client-lib/src/lib/editor/editor-body-visual/card-template.ts
  libs/client-lib/src/lib/editor/editor-body-visual/editor-body-visual.component.html
  libs/client-lib/src/lib/editor/editor-body-visual/editor-body-visual.component.ts
  libs/client-lib/src/lib/editor/editor-body-visual/player-template.ts
Labels: type:enhancement, priority:high, scope:ui

#372 Visual fixes
  libs/client-lib/src/lib/admin/admin-reports/admin-reports.component.html
  libs/client-lib/src/lib/admin/admin-scripts/admin-scripts.component.ts
  libs/client-lib/src/lib/admin/admin/admin.component.html
  libs/client-lib/src/lib/board-game-search/board-game-search/board-game-search.component.html
  libs/client-lib/src/lib/board-game-search/board-game-search/board-game-search.component.scss
  templates/script.js
Labels: type:bug, priority:high, scope:ui, type:cosmetic

#374 ✨(VDSL): header recoloured, looping structures now able to have elements put in
  apps/client/tailwind.config.js
  libs/client-lib/src/lib/editor/editor-body-visual/editor-body-visual.component.scss
  libs/client-lib/src/lib/editor/editor-body-visual/editor-body-visual.component.ts
  libs/client-lib/src/lib/editor/editor-body-visual/element-template.ts
  libs/client-lib/src/lib/editor/editor-body-visual/loop-template.ts
  libs/client-lib/src/lib/editor/editor-body/editor-body.component.ts
  libs/client-lib/src/lib/shared/components/header/header.component.html
  libs/client-lib/src/lib/shared/components/header/header.component.scss
  tailwind.config.js
Labels: type:enhancement, priority:high, scope:ui

#377 UI update on collections page.
  libs/client-lib/src/lib/admin/admin/admin.component.spec.ts
  libs/client-lib/src/lib/collections/collections/collections.component.html
  libs/client-lib/src/lib/collections/collections/collections.component.scss
  libs/client-lib/src/lib/scripts/automata-scripts/automata-scripts.component.spec.ts
  libs/client-lib/src/lib/shared/components/header/header.component.spec.ts
  yarn.lock
Labels: priority:high

#379 (VDSL): removing elements and consider added to methods
  libs/client-lib/src/lib/editor/editor-body-visual/card-template.ts
  libs/client-lib/src/lib/editor/editor-body-visual/editor-body-visual.component.ts
  libs/client-lib/src/lib/editor/editor-body-visual/element-template.ts
  libs/client-lib/src/lib/editor/editor-body-visual/loop-template.ts
  libs/client-lib/src/lib/editor/editor-body-visual/player-template.ts
  libs/client-lib/src/lib/editor/editor-body/editor-body.component.ts
Labels: type:enhancement, priority:high, scope:ui

#382 UI minor fix (Pease Yarn Install)
  apps/client/src/app/app.module.ts
  apps/client/src/assets/globalstylesheet/global.scss
  libs/client-lib/src/lib/board-game-details/board-game-details/board-game-details.component.html
  libs/client-lib/src/lib/board-game-details/board-game-details/board-game-details.component.scss
  libs/client-lib/src/lib/editor/editor-help/editor-help.component.html
  libs/client-lib/src/lib/game-sessions/game-sessions/game-sessions.component.html
  libs/client-lib/src/lib/game-sessions/game-sessions/game-sessions.component.scss
  libs/client-lib/src/lib/home/home/home.component.html
  libs/client-lib/src/lib/home/home/home.component.scss
  libs/client-lib/src/lib/script-detail/script-detail/script-detail.component.html
  libs/client-lib/src/lib/script-detail/script-detail/script-detail.component.scss
  libs/client-lib/src/lib/scripts/main-scripts/main-scripts.component.html
  libs/client-lib/src/lib/scripts/main-scripts/main-scripts.component.scss
  libs/client-lib/src/lib/scripts/main-scripts/main-scripts.component.ts
  libs/client-lib/src/lib/scripts/scripts.module.ts
  libs/client-lib/src/lib/shared/components/header/header.component.ts
  package.json
  yarn.lock
Labels: scope:ui

#386 (VDSL): fixes
  libs/client-lib/src/lib/editor/editor-body-visual/card-template.ts
  libs/client-lib/src/lib/editor/editor-body-visual/editor-body-visual.component.scss
  libs/client-lib/src/lib/editor/editor-body-visual/player-template.ts
  libs/client-lib/src/lib/editor/editor-body/editor-body.component.ts
Labels: priority:high, scope:ui, type:cosmetic

#387 (VDSL): changes
  libs/client-lib/src/lib/editor/editor-body-visual/editor-body-visual.component.scss
  libs/client-lib/src/lib/editor/editor-body-visual/element-template.ts
  libs/client-lib/src/lib/editor/editor-body-visual/loop-template.ts
  libs/client-lib/src/lib/editor/editor-body/editor-body.component.ts
Labels: type:bug, priority:high, scope:ui

#389 (VDSL): if content editable
  libs/client-lib/src/lib/editor/editor-body-visual/element-template.ts
  libs/client-lib/src/lib/editor/editor-body-visual/loop-template.ts
  libs/client-lib/src/lib/editor/editor-body/editor-body.component.ts
Labels: type:enhancement, priority:high, scope:ui

#390 fixes
  libs/client-lib/src/lib/editor/editor-body/editor-body.component.ts
Labels: type:bug, priority:high, scope:ui

#391 :up:
  package-lock.json
  yarn.lock
Labels: type:bug, priority:high, scope:cicd

#394 (VDSL): while parameters editable
  libs/client-lib/src/lib/editor/editor-body-visual/element-template.ts
  libs/client-lib/src/lib/editor/editor-body-visual/loop-template.ts
  libs/client-lib/src/lib/editor/editor-body/editor-body.component.ts
Labels: type:enhancement, priority:high, scope:ui

#396 Adding Documentation.
  libs/api-lib/src/lib/controllers/comments/comment.controller.spec.ts
  libs/api-lib/src/lib/services/downloads/downloads.service.spec.ts
  libs/api-lib/src/lib/services/models/models.service.spec.ts
  libs/api-lib/src/lib/services/mongodb-storage/mongodb-storage.service.spec.ts
  libs/api-lib/src/lib/services/ratings/rating.service.spec.ts
  libs/client-lib/src/lib/admin/report-form/report-form.component.spec.ts
  libs/client-lib/src/lib/client-lib-routing.module.spec.ts
  libs/client-lib/src/lib/models/models/models.component.spec.ts
  libs/client-lib/src/lib/script-detail/report-form/report-form.component.spec.ts
  yarn.lock
Labels: priority:high, scope:documentation
