Repository COS301-SE-2022/Board-Game-Companion-App, pull requests merged in 2022-07, with the labels that each got.

#156 🚧 Adding pagination to the table
  libs/client-lib/src/lib/admin/admin.module.ts
  libs/client-lib/src/lib/admin/admin/admin.component.html
  libs/client-lib/src/lib/admin/admin/admin.component.spec.ts
  libs/client-lib/src/lib/admin/admin/admin.component.ts
  package.json
  yarn.lock
Labels: type:enhancement, priority:high, scope:ui

#157 pwa dependecies
  apps/client/project.json
  apps/client/src/app/app.module.ts
Labels: type:enhancement, priority:medium, scope:ui

#159 :bug: Header fixed
  env
  libs/client-lib/src/lib/shared/components/header/header.component.html
  libs/client-lib/src/lib/shared/components/header/header.component.ts
Labels: type:bug, priority:high, scope:ui

#161 🎨 updates on admin page.
  .gitignore
  env
  libs/client-lib/src/lib/admin/admin.module.ts
  libs/client-lib/src/lib/admin/admin/admin.component.html
  libs/client-lib/src/lib/admin/admin/admin.component.ts
  libs/client-lib/src/lib/editor/editor-body/editor-body.component.ts
  libs/client-lib/src/lib/editor/editor/editor.component.ts
  libs/client-lib/src/lib/script-detail/script-detail/script-detail.component.ts
Labels: priority:high, scope:ui

#162 ✅ Fix testing issue
  libs/api-lib/src/lib/services/comments/comment.service.spec.ts
  libs/api-lib/src/lib/services/ratings/rating.service.spec.ts
Labels: priority:high, scope:cicd

#165 ✅ Added tests.
  libs/client-lib/src/lib/add-to-collection/add-to-collection/add-to-collection.component.spec.ts
  libs/client-lib/src/lib/board-game-search/bgg-search-service/bgg-search.service.spec.ts
  libs/client-lib/src/lib/board-game-search/board-game-search/board-game-search.component.spec.ts
  libs/client-lib/src/lib/board-game-search/pagination/pagination.component.spec.ts
  libs/client-lib/src/lib/editor/editor-body/editor-body.component.spec.ts
  libs/client-lib/src/lib/editor/editor/editor.component.spec.ts
  libs/client-lib/src/lib/game-sessions/game-sessions/game-sessions.component.spec.ts
  libs/client-lib/src/lib/google-login/GoogleAuth/google-auth.service.spec.ts
  libs/client-lib/src/lib/google-login/google-login.component.spec.ts
  libs/client-lib/src/lib/google-login/google-login.component.ts
  libs/client-lib/src/lib/home/carousel/carousel.component.spec.ts
  libs/client-lib/src/lib/home/home/home.component.spec.ts
  libs/client-lib/src/lib/script-detail/comment-form/comment-form.component.spec.ts
  libs/client-lib/src/lib/script-detail/comment-section/comment-section.component.spec.ts
  libs/client-lib/src/lib/script-detail/comment/comment.component.spec.ts
  libs/client-lib/src/lib/script-detail/script-detail-service/script-detail.service.spec.ts
  libs/client-lib/src/lib/script-detail/script-detail/script-detail.component.spec.ts
Labels: type:enhancement, priority:medium, scope:ui

#168 :lipstick:(UI): Header, Footer and Collections Page Rework
  apps/client/src/assets/globalstylesheet/global.scss
  apps/client/src/assets/images/Dice.png
  libs/client-lib/src/lib/collections/collections/collections.component.html
  libs/client-lib/src/lib/collections/collections/collections.component.scss
  libs/client-lib/src/lib/shared/components/footer/footer.component.html
  libs/client-lib/src/lib/shared/components/footer/footer.component.scss
  libs/client-lib/src/lib/shared/components/header/header.component.html
  libs/client-lib/src/lib/shared/components/header/header.component.scss
  libs/client-lib/src/lib/shared/components/header/header.component.ts
Labels: priority:high, scope:ui, type:cosmetic

#170 💄(UI): View Collection Page re-styled
  .vscode/settings.json
  libs/client-lib/src/lib/collections/collections/collections.component.html
  libs/client-lib/src/lib/view-collection/view-collection/view-collection.component.html
  libs/client-lib/src/lib/view-collection/view-collection/view-collection.component.scss
  libs/client-lib/src/lib/view-collection/view-collection/view-collection.component.ts
Labels: priority:medium, scope:ui, type:cosmetic

#171 💄(UI): Game Sessions Page re-styled
  libs/client-lib/src/lib/game-sessions/game-sessions/game-sessions.component.html
  libs/client-lib/src/lib/game-sessions/game-sessions/game-sessions.component.scss
  libs/client-lib/src/lib/view-collection/view-collection/view-collection.component.html
Labels: priority:medium, scope:ui, type:cosmetic

#172 💄(UI): Sessions Page re-styled
  libs/client-lib/src/lib/session/session/session.component.html
  libs/client-lib/src/lib/session/session/session.component.scss
Labels: type:enhancement, priority:medium, scope:ui

#175 Added all rules to parser
  libs/api-lib/src/lib/services/compiler/compiler.service.ts
Labels: type:enhancement, priority:high, scope:api

#178 PWA (mobile responsive header)
  apps/client/src/assets/icons/icon-128x128.png
  apps/client/src/assets/icons/icon-144x144.png
  apps/client/src/assets/icons/icon-152x152.png
  apps/client/src/assets/icons/icon-192x192.png
  apps/client/src/assets/icons/icon-384x384.png
  apps/client/src/assets/icons/icon-48x48.png
  apps/client/src/assets/icons/icon-512x512.png
  apps/client/src/assets/icons/icon-72x72.png
  apps/client/src/assets/icons/icon-96x96.png
  apps/client/src/manifest.webmanifest
  apps/client/src/styles.scss
  libs/client-lib/src/lib/collections/collections/collections.component.html
  libs/client-lib/src/lib/collections/collections/collections.component.scss
  libs/client-lib/src/lib/editor/editor-tool-bar/editor-tool-bar.component.html
  libs/client-lib/src/lib/editor/editor-tool-bar/editor-tool-bar.component.spec.ts
  libs/client-lib/src/lib/editor/editor-tool-bar/editor-tool-bar.component.ts
  libs/client-lib/src/lib/google-login/google-login.component.html
  libs/client-lib/src/lib/google-login/google-login.component.scss
  libs/client-lib/src/lib/google-login/google-login.component.ts
  libs/client-lib/src/lib/script-detail/script-detail/script-detail.component.html
  libs/client-lib/src/lib/scripts/scripts/scripts.component.scss
  libs/client-lib/src/lib/shared/components/footer/footer.component.html
  libs/client-lib/src/lib/shared/components/header/header.component.html
  libs/client-lib/src/lib/shared/components/header/header.component.scss
  libs/client-lib/src/lib/shared/components/header/header.component.ts
Labels: priority:high, scope:ui, scope:services

#179 Fixed Header
  libs/client-lib/src/lib/collections/collections/collections.component.html
  libs/client-lib/src/lib/collections/collections/collections.component.scss
  libs/client-lib/src/lib/shared/components/footer/footer.component.html
  libs/client-lib/src/lib/shared/components/header/header.component.html
  libs/client-lib/src/lib/shared/components/header/header.component.scss
Labels: type:bug, type:enhancement, priority:high, scope:ui

#180 🎨 fixed formatting
  libs/client-lib/src/lib/collections/collections/collections.component.html
  libs/client-lib/src/lib/collections/collections/collections.component.scss
Labels: type:enhancement, priority:medium, type:cosmetic

#181 💄(UI): View Collections fix
  libs/client-lib/src/lib/collections/collections/collections.component.html
  libs/client-lib/src/lib/shared/components/header/header.component.html
  libs/client-lib/src/lib/shared/components/header/header.component.scss
  libs/client-lib/src/lib/view-collection/view-collection/view-collection.component.html
  libs/client-lib/src/lib/view-collection/view-collection/view-collection.component.scss
Labels: priority:medium, scope:ui, type:cosmetic

#182 Parser
  libs/api-lib/src/lib/services/compiler/compiler.service.ts
Labels: type:bug, type:enhancement, priority:high, scope:api

#184 🚧 ui updates
  libs/client-lib/src/lib/admin/admin/admin.component.html
  libs/client-lib/src/lib/admin/admin/admin.component.scss
  libs/client-lib/src/lib/editor/editor-tool-bar/editor-tool-bar.component.spec.ts
Labels: priority:high, scope:ui, type:cosmetic

#185 💄(UI): Board Games page partial re-design
  libs/client-lib/src/lib/board-game-search/board-game-search/board-game-search.component.html
  libs/client-lib/src/lib/board-game-search/board-game-search/board-game-search.component.scss
  libs/client-lib/src/lib/board-game-search/pagination/pagination.component.html
  libs/client-lib/src/lib/game-sessions/game-sessions/game-sessions.component.html
  libs/client-lib/src/lib/game-sessions/game-sessions/game-sessions.component.scss
  libs/client-lib/src/lib/shared/components/header/header.component.html
  libs/client-lib/src/lib/shared/components/header/header.component.scss
Labels: priority:low, scope:ui, type:cosmetic

#186 (mobile view)View Collection
  libs/client-lib/src/lib/add-to-collection/add-to-collection/add-to-collection.component.scss
  libs/client-lib/src/lib/board-game-details/board-game-details/board-game-details.component.html
  libs/client-lib/src/lib/board-game-details/board-game-details/board-game-details.component.scss
  libs/client-lib/src/lib/editor/editor-body/editor-body.component.scss
  libs/client-lib/src/lib/editor/editor/editor.component.scss
  libs/client-lib/src/lib/game-sessions/game-sessions/game-sessions.component.html
  libs/client-lib/src/lib/game-sessions/game-sessions/game-sessions.component.scss
  libs/client-lib/src/lib/home/carousel1/carousel1.component.html
  libs/client-lib/src/lib/home/carousel1/carousel1.component.scss
  libs/client-lib/src/lib/home/carousel2/carousel2.component.html
  libs/client-lib/src/lib/home/carousel2/carousel2.component.scss
  libs/client-lib/src/lib/home/home/home.component.html
  libs/client-lib/src/lib/home/home/home.component.scss
  libs/client-lib/src/lib/view-collection/view-collection/view-collection.component.html
  libs/client-lib/src/lib/view-collection/view-collection/view-collection.component.scss
Labels: priority:medium, scope:ui, type:cosmetic

#187 mobile view fix
  libs/client-lib/src/lib/home/home/home.component.scss
Labels: priority:low, scope:ui, type:cosmetic

#190 JS template start
  libs/api-lib/src/lib/services/compiler/compiler.service.ts
  libs/api-lib/src/lib/services/compiler/template_script.js
Labels: type:enhancement, priority:high, scope:api

#191 :poop: I think it works?
  libs/api-lib/src/lib/services/compiler/compiler.service.ts
  package.json
  yarn.lock
Labels: type:bug, priority:high, scope:api

#192 Parser fix
  libs/api-lib/src/lib/services/compiler/compiler.service.ts
Labels: type:bug, priority:high, scope:api

#194 :bug: Fixed identifier token
  libs/api-lib/src/lib/services/compiler/compiler.service.ts
  libs/client-lib/src/lib/shared/components/footer/footer.component.ts
Labels: type:bug, priority:high, scope:api

#197 Re added executor, started CST visits
  libs/api-lib/src/lib/services/compiler/compiler.service.ts
  libs/client-lib/src/lib/client-lib-routing.module.ts
  libs/client-lib/src/lib/script-executor/script-executor/script-executor.component.ts
  libs/client-lib/src/lib/shared/components/footer/footer.component.ts
Labels: type:bug, type:enhancement, priority:high, scope:api

#198 🚧 functionality updates
  libs/client-lib/src/lib/admin/admin/admin.component.ts
  libs/client-lib/src/lib/board-game-search/board-game-search/board-game-search.component.html
  libs/client-lib/src/lib/board-game-search/board-game-search/board-game-search.component.ts
  libs/client-lib/src/lib/collections/collections/collections.component.ts
  libs/client-lib/src/lib/game-sessions/game-sessions/game-sessions.component.ts
  libs/client-lib/src/lib/shared/components/header/header.component.html
  libs/client-lib/src/lib/shared/components/header/header.component.ts
  libs/client-lib/src/lib/shared/shared.module.ts
  libs/client-lib/src/lib/view-collection/view-collection/view-collection.component.ts
Labels: type:bug, type:enhancement, priority:high, scope:ui

#199 💩(UI): Addition of Input and Output methods for Script Executer
  libs/client-lib/src/lib/script-executor/script-executor/script-executor.component.html
  libs/client-lib/src/lib/script-executor/script-executor/script-executor.component.ts
  libs/client-lib/src/lib/shared/components/header/header.component.ts
Labels: type:enhancement, priority:low, scope:ui

#200 🐛 button fix
  libs/client-lib/src/lib/admin/admin/admin.component.html
Labels: type:enhancement, priority:medium, scope:ui

#201 Added Visitors for state, players, definitions
  libs/api-lib/src/lib/services/compiler/compiler.service.ts
  libs/api-lib/src/lib/services/compiler/template_script.js
  package.json
  yarn.lock
Labels: type:enhancement, priority:high, scope:api

#202 💄(UI): Completion of Board Games Page
  libs/client-lib/src/lib/board-game-details/board-game-details/board-game-details.component.ts
  libs/client-lib/src/lib/board-game-search/board-game-search/board-game-search.component.html
  libs/client-lib/src/lib/board-game-search/board-game-search/board-game-search.component.scss
  libs/client-lib/src/lib/board-game-search/board-game-search/board-game-search.component.ts
Labels: type:enhancement, priority:low, scope:ui

#203 More visitor functionality
  libs/api-lib/src/lib/services/compiler/compiler.service.ts
  libs/api-lib/src/lib/services/compiler/template_script.js
  libs/client-lib/src/lib/shared/components/footer/footer.component.ts
Labels: type:bug, type:enhancement, priority:high, scope:api

#207 :bug: visitor fixes continue
  libs/api-lib/src/lib/services/compiler/compiler.service.ts
  libs/api-lib/src/lib/services/scripts/script.service.ts
  templates/script.js
  templates/test.js
Labels: type:bug, priority:high, scope:api

#209 💄(UI): Redesign of add to collections page
  libs/client-lib/src/lib/add-to-collection/add-to-collection/add-to-collection.component.html
  libs/client-lib/src/lib/add-to-collection/add-to-collection/add-to-collection.component.scss
  libs/client-lib/src/lib/add-to-collection/add-to-collection/add-to-collection.component.ts
Labels: priority:low, scope:ui, type:cosmetic

#210 Mobile board games
  apps/client/src/app/app.component.spec.ts
  apps/client/src/app/app.module.ts
  libs/client-lib/src/index.ts
  libs/client-lib/src/lib/board-game-search/board-game-search/board-game-search.component.html
  libs/client-lib/src/lib/board-game-search/board-game-search/board-game-search.component.scss
  libs/client-lib/src/lib/models/models/models.component.spec.ts
  libs/client-lib/src/lib/models/train/train.component.spec.ts
Labels: priority:medium, scope:ui, type:cosmetic

#212 More visitor functionality, added semantics for pieces
  libs/api-lib/src/lib/services/compiler/compiler.service.ts
  libs/client-lib/src/lib/editor/editor/editor.component.ts
  templates/script.js
  templates/test.js
Labels: type:bug, type:enhancement, priority:high, scope:api

#213 fixed mobile view (board game search)
  libs/client-lib/src/lib/board-game-search/board-game-search/board-game-search.component.html
  libs/client-lib/src/lib/board-game-search/board-game-search/board-game-search.component.scss
  libs/client-lib/src/lib/models/train/train.component.spec.ts
Labels: type:bug, priority:medium, scope:ui, type:cosmetic

#214 add-to-collection mobile breakpoint
  libs/client-lib/src/lib/add-to-collection/add-to-collection/add-to-collection.component.html
  libs/client-lib/src/lib/add-to-collection/add-to-collection/add-to-collection.component.scss
  libs/client-lib/src/lib/game-sessions/game-sessions/game-sessions.component.scss
Labels: type:enhancement, priority:medium, type:cosmetic

#211 ✅ update to the ui tests.
  apps/client/src/app/app.component.spec.ts
  libs/client-lib/src/lib/admin/admin-service/admin.service.spec.ts
  libs/client-lib/src/lib/admin/admin/admin.component.html
  libs/client-lib/src/lib/admin/admin/admin.component.spec.ts
  libs/client-lib/src/lib/admin/admin/admin.component.ts
  libs/client-lib/src/lib/board-game-details/board-game-details/board-game-details.component.spec.ts
  libs/client-lib/src/lib/board-game-search/board-game-search/board-game-search.component.spec.ts
  libs/client-lib/src/lib/editor/editor/editor.component.spec.ts
  libs/client-lib/src/lib/scripts/scripts/scripts.component.spec.ts
  libs/client-lib/src/lib/scripts/tool-bar/tool-bar.component.spec.ts
  libs/client-lib/src/lib/scripts/update-script/update-scripts.component.spec.ts
  libs/client-lib/src/lib/shared/services/comments/comment.service.spec.ts
  libs/client-lib/src/lib/shared/services/scripts/script.service.spec.ts
Labels: priority:medium, scope:ui

#215 general component test and (resize) script detail page
  libs/client-lib/src/lib/models/general/general.component.spec.ts
  libs/client-lib/src/lib/script-detail/script-detail/script-detail.component.html
  libs/client-lib/src/lib/script-detail/script-detail/script-detail.component.scss
Labels: type:enhancement, priority:medium, scope:ui, scope:services

#216 Visitor functionality added
  libs/api-lib/src/lib/services/compiler/compiler.service.ts
  libs/client-lib/src/lib/editor/editor/editor.component.ts
  templates/ActionTemplate.js
  templates/script.js
  templates/test.js
Labels: type:bug, type:enhancement, priority:high, scope:api

#218 Compiler Update
  libs/api-lib/src/lib/services/compiler/compiler.service.ts
  libs/client-lib/src/lib/editor/editor/editor.component.ts
  libs/client-lib/src/lib/script-executor/script-executor/script-executor.component.html
  libs/client-lib/src/lib/script-executor/script-executor/script-executor.component.ts
  templates/ActionTemplate.js
  templates/script.js
  templates/test.js
Labels: priority:high

#219 💄(UI): Board game details redesign implementation, small visual fixes…
  libs/client-lib/src/lib/add-to-collection/add-to-collection/add-to-collection.component.ts
  libs/client-lib/src/lib/board-game-details/board-game-details/board-game-details.component.html
  libs/client-lib/src/lib/board-game-details/board-game-details/board-game-details.component.scss
  libs/client-lib/src/lib/board-game-details/board-game-details/board-game-details.component.ts
  libs/client-lib/src/lib/home/home/home.component.html
  libs/client-lib/src/lib/home/home/home.component.ts
  libs/client-lib/src/lib/script-executor/script-executor/script-executor.component.ts
  libs/client-lib/src/lib/shared/components/header/header.component.ts
  package.json
  tailwind.config.js
  yarn.lock
Labels: type:enhancement, priority:low, scope:ui, type:cosmetic

#217 minor fix
  libs/client-lib/src/lib/home/home/home.component.scss
  libs/client-lib/src/lib/scripts/scripts/scripts.component.html
  libs/client-lib/src/lib/scripts/scripts/scripts.component.scss
  libs/client-lib/src/lib/scripts/scripts/scripts.component.ts
Labels: priority:medium, scope:ui

#223 🐛(UI): Visual bug fixes
  libs/client-lib/src/lib/board-game-search/board-game-search/board-game-search.component.html
  libs/client-lib/src/lib/board-game-search/board-game-search/board-game-search.component.scss
  libs/client-lib/src/lib/game-sessions/game-sessions/game-sessions.component.html
  libs/client-lib/src/lib/home/carousel1/carousel1.component.ts
  libs/client-lib/src/lib/home/home/home.component.scss
  libs/client-lib/src/lib/script-detail/comment-form/comment-form.component.html
  libs/client-lib/src/lib/script-detail/comment-form/comment-form.component.scss
  libs/client-lib/src/lib/script-detail/script-detail/script-detail.component.html
  libs/client-lib/src/lib/script-detail/script-detail/script-detail.component.scss
  libs/client-lib/src/lib/shared/components/header/header.component.html
  libs/client-lib/src/lib/shared/components/header/header.component.ts
  libs/client-lib/src/lib/view-collection/view-collection/view-collection.component.html
  libs/client-lib/src/lib/view-collection/view-collection/view-collection.component.scss
  yarn.lock
Labels: priority:low, scope:ui, type:cosmetic

#222 🚧 update to login functionality
  libs/client-lib/src/lib/add-to-collection/add-to-collection/add-to-collection.component.spec.ts
  libs/client-lib/src/lib/board-game-search/board-game-search/board-game-search.component.spec.ts
  libs/client-lib/src/lib/board-game-search/pagination/pagination.component.spec.ts
  libs/client-lib/src/lib/client-lib-routing.module.spec.ts
  libs/client-lib/src/lib/client-lib-routing.module.ts
  libs/client-lib/src/lib/collections/collections/collections.component.spec.ts
  libs/client-lib/src/lib/collections/collections/collections.component.ts
  libs/client-lib/src/lib/editor/editor/editor.component.spec.ts
  libs/client-lib/src/lib/google-login/GoogleAuth/google-auth.service.ts
  libs/client-lib/src/lib/google-login/google-login.module.ts
  libs/client-lib/src/lib/models/general/general.component.spec.ts
  libs/client-lib/src/lib/models/train/train.component.spec.ts
  libs/client-lib/src/lib/script-executor/script-executor/script-executor.component.spec.ts
  libs/client-lib/src/lib/shared/components/header/header.component.ts
Labels: priority:high

#225 minor fix display
  libs/client-lib/src/lib/scripts/scripts/scripts.component.html
  libs/client-lib/src/lib/scripts/scripts/scripts.component.scss
Labels: priority:medium, scope:ui, type:cosmetic

#226 ✅ update to tests
  libs/client-lib/src/lib/client-lib-routing.module.spec.ts
  libs/client-lib/src/lib/scripts/scripts/scripts.component.html
  libs/client-lib/src/lib/scripts/scripts/scripts.component.ts
Labels: priority:high

#227 🐛 minor fix script
  libs/client-lib/src/lib/scripts/scripts/scripts.component.scss
Labels: priority:low, scope:ui

#228 compiler and script update
  libs/api-lib/src/lib/services/compiler/compiler.service.ts
  libs/client-lib/src/lib/editor/editor/editor.component.ts
  libs/client-lib/src/lib/script-executor/script-executor/script-executor.component.html
  templates/script.js
  templates/test.js
Labels: type:enhancement, priority:high, scope:api

#230 🐛Visual bug fixes
  libs/client-lib/src/lib/board-game-details/board-game-details/board-game-details.component.html
  libs/client-lib/src/lib/board-game-details/board-game-details/board-game-details.component.scss
  libs/client-lib/src/lib/scripts/scripts/scripts.component.html
  libs/client-lib/src/lib/scripts/scripts/scripts.component.ts
  libs/client-lib/src/lib/session/session/session.component.html
  libs/client-lib/src/lib/shared/components/header/header.component.html
Labels: type:bug, priority:low, scope:ui, type:cosmetic

#231 🐛 changing author datatype
  libs/client-lib/src/lib/admin/admin/admin.component.html
  libs/client-lib/src/lib/admin/admin/admin.component.spec.ts
  libs/client-lib/src/lib/admin/admin/admin.component.ts
  libs/client-lib/src/lib/scripts/scripts/scripts.component.spec.ts
Labels: type:bug, priority:high

#232 Parser
  libs/api-lib/src/lib/services/compiler/compiler.service.ts
  libs/client-lib/src/lib/editor/editor/editor.component.ts
  libs/client-lib/src/lib/script-executor/script-executor/script-executor.component.ts
  templates/script.js
Labels: type:bug, type:enhancement, priority:high, scope:api

#234 💩(UI): Session data acquisition from script execution
  libs/client-lib/src/lib/board-game-search/board-game-search/board-game-search.component.html
  libs/client-lib/src/lib/board-game-search/board-game-search/board-game-search.component.scss
  libs/client-lib/src/lib/script-executor/script-executor/script-executor.component.ts
Labels: priority:low, scope:ui, type:cosmetic

#235 🥇 Update editor.component.ts
  libs/client-lib/src/lib/editor/editor/editor.component.ts
Labels: type:bug, priority:high, scope:ui

#236 ✅ fix tests
  libs/client-lib/src/lib/script-executor/script-executor/script-executor.component.spec.ts
Labels: type:bug, priority:medium
